src/integrations/iron_handlers.rs, src/lib.rs
This should be the responsibility of the caller and makes it consistent
with how the successful case is handled.
=> Remove JSON wrapper object from GraphQLError::to_json

src/lib.rs, src/macros/args.rs, src/macros/field.rs, src/macros/input_object.rs, src/macros/interface.rs, src/macros/object.rs
This function is transforming snake_case to camelCase.
This may be considered a breaking change since the function is publicly exported, but it is hidden from the documentation.
=> Rename erroneously named to_snake_case

Cargo.toml, src/integrations/mod.rs, src/integrations/serde.rs, src/lib.rs
This adds the Serde serialization trait to the following:
* `ExecutionError`
* `GraphQLError`
* `InputValue` (+ deserialization)
* `RuleError`
* `SourcePosition`
* `Spanning<ParseError>`
* `Value`
Serde support is enabled via the "serde" feature flag.
=> Add optional Serde serialization support

Cargo.toml, src/ast.rs, src/integrations/mod.rs, src/integrations/rustc_serialize.rs, src/lib.rs, src/schema/schema.rs, src/value.rs
This extracts rustc-serialize JSON serialization into its own module,
decoupling all core structures from its use.
rustc-serialize can now be completely disabled, removing it as a
dependency if serde (or none) is used instead. It is, however, still the
default serializer. In Cargo, the `default-features` field must be set
to `false` to disable it, e.g.,
[dependencies.juniper]
version = "0.6"
default-features = false
features = ["serde"]
The Iron handlers still require rustc-serialize.
The default values for attributes changed from being formatted as JSON
to how it is defined in [the reference implementation][printer.js].
[printer.js]: https://github.com/graphql/graphql-js/blob/v0.8.2/src/language/printer.js
=> Make rustc-serialize optional

src/integrations/iron_handlers.rs
`params.variables` is already an object when passed to the fetcher and
does not need to be parsed.
=> Fix graphQLFetcher body serialization

src/types/scalars.rs
ID is a named tuple with a private String field. This prevents any
creation of an ID outside its own module. Traits, such as conversion and
dereference, are added to make ID usable without exposing its inner
field.
=> Implement traits for ID to make it usable outside its module

src/executor_tests/variables.rs, src/parser/value.rs, src/types/utilities.rs, src/validation/multi_visitor.rs, src/validation/rules/arguments_of_correct_type.rs, src/validation/traits.rs, src/validation/visitor.rs
Explicit `null` values are valid for nullable input values. See
<https://facebook.github.io/graphql/#sec-Types.Non-Null>.
Fixes #23
=> Accept explicit null input values in queries

Cargo.toml, examples/server.rs, src/integrations/iron_handlers.rs
* `Url::into_generic_url` was deprecated in 0.4.1. The `Into` trait is
used instead.
* iron/logger removed support for ANSI terminal colors in 0.2.0, which
makes logging work in the Command Prompt on Windows.
Fixes #21
=> Update to iron 0.5

src/parser/document.rs, src/parser/parser.rs, src/parser/utils.rs, src/parser/value.rs
Hey,
I noticed this panic while passing invalid GraphQL queries to `juniper`.
I've moved it to the `ParseError::UnexpectedEndOfFile` error instead of panicking.
=> Remove panic in Parser::next

src/value.rs
Another bigger source of allocations: `Value::object` is often called with a `HashMap<String, Value`>, in which case calling `as_ref()` and `to_owned()` on the `String` will result in a needless copy.
Changing the required trait to `Into<String>` still works for `str` and `Cow<str>`, but ensures that `String` is not copied.
=> Try to avoid cloning in Value::object

src/lib.rs, src/macros/input_object.rs
For bigger schemas that leverage the `graphql_*` macros, `to_camel_case` is a major source of allocations.
This is because even if the compiler is able to fully evaluate the transformation at compile time, the program still needs to perform at least one allocation whenever `GraphQLType::resolve_field` is called.
This patch improves the best-case performance of `to_camel_case` using `Cow`, so that zero allocations and copies are necessary if no `_` are present in the field name (in my application this applies to most of the fields).
=> Improve best-case performance for to_camel_case

src/validation/mod.rs, src/validation/multi_visitor.rs, src/validation/rules/mod.rs, src/validation/test_harness.rs
Get rid of all the boxing/heap allocations in `visit_all_rules`, and rely on a stack-allocated heterogenous linked list instead.
In my small GraphQL application (use-case is a high volume of rather simple queries), this brings me from about 17k to 20k rps. Working on getting some more detailed and relevant numbers, in the meantime I thought I'd already put this up for review.
Let me know what you think!
=> Avoid boxing in MultiVisitor

juniper/src/ast.rs, juniper/src/executor.rs, juniper/src/macros/args.rs, juniper/src/macros/enums.rs, juniper/src/macros/field.rs, juniper/src/macros/input_object.rs, juniper/src/macros/interface.rs, juniper/src/macros/object.rs, juniper/src/macros/scalar.rs, juniper/src/macros/union.rs, juniper/src/parser/document.rs, juniper/src/schema/meta.rs, juniper/src/schema/model.rs, juniper/src/schema/schema.rs, juniper/src/tests/mod.rs, juniper/src/tests/type_info_tests.rs, juniper/src/types/base.rs, juniper/src/types/containers.rs, juniper/src/types/pointers.rs, juniper/src/types/scalars.rs, juniper/src/validation/rules/overlapping_fields_can_be_merged.rs, juniper/src/validation/rules/variables_in_allowed_position.rs, juniper/src/validation/test_harness.rs, juniper/src/validation/visitor.rs, juniper_codegen/src/derive_enum.rs, juniper_codegen/src/derive_input_object.rs, juniper_codegen/src/derive_object.rs, juniper_tests/src/codegen/derive_enum.rs, juniper_tests/src/codegen/derive_input_object.rs, juniper_tests/src/codegen/derive_object.rs
Hi!
Apologies in advance for the somewhat large patch.
This is my first attempt at a feature contribution. The feature I'm trying to implement scratches an itch of my own, and has been in-use in a project of mine for quite some time now and I thought it might be nice to try and contribute it back up-stream. So I took the time today to rebase it and clean it up.
To frame the problem, I'm working on a database that provides a GraphQL-based API. The objects stored in the database are defined using a schema which the user can configure. The schema will be loaded from a configuration file at start-up.
Previously, it was only possible to define the GraphQL schema at compile time, due to the fact that the `name` and `type` methods in the `GraphQLType` trait do not take any objects as arguments …
=> Implement support for dynamic schemas

juniper/src/executor.rs, juniper/src/schema/model.rs, juniper/src/types/mod.rs, juniper/src/types/name.rs
Sets up some basic infrastructure for name validation and hooks it up to the registry.
In terms of error messages I tried to stick to the [reference implementation](https://github.com/graphql/graphql-js/blob/7ddd8dd44cb7f8a3a9f7a760d5ab76ac91802931/src/utilities/assertValidName.js#L53).
As a next step we could explore if/how to leverage `Name::is_valid` from the codegen to provide compile-time errors for invalid names, perhaps via the upcoming [`compile_error!`](https://github.com/sgrif/rfcs/blob/sg-add-error-macro/text/0000-add-error-macro.md) macro, or simply via `panic!`-ing (would love your guidance on that, @theduke).
Fixes #72
=> Reject types with invalid names

juniper/src/ast.rs, juniper/src/executor.rs, juniper/src/integrations/uuid.rs, juniper/src/macros/enums.rs, juniper/src/macros/input_object.rs, juniper/src/macros/scalar.rs, juniper/src/macros/tests/input_object.rs, juniper/src/schema/meta.rs, juniper/src/types/containers.rs, juniper/src/types/pointers.rs, juniper/src/types/scalars.rs, juniper/src/validation/test_harness.rs, juniper/src/value.rs, juniper_codegen/src/derive_enum.rs, juniper_codegen/src/derive_input_object.rs, juniper_tests/src/codegen/derive_enum.rs, juniper_tests/src/codegen/derive_input_object.rs
* Rename FromInputValue::from to from_input_value
* Rename ToInputValue::to to to_input_value
Fixes #56 .
=> Rename input value methods

CHANGELOG.md, juniper/Cargo.toml, juniper/src/ast.rs, juniper/src/executor_tests/directives.rs, juniper/src/executor_tests/enums.rs, juniper/src/executor_tests/executor.rs, juniper/src/executor_tests/variables.rs, juniper/src/integrations/serde.rs, juniper/src/lib.rs, juniper/src/macros/tests/enums.rs, juniper/src/macros/tests/field.rs, juniper/src/macros/tests/input_object.rs, juniper/src/macros/tests/interface.rs, juniper/src/macros/tests/object.rs, juniper/src/macros/tests/scalar.rs, juniper/src/macros/tests/union.rs, juniper/src/parser/tests/value.rs, juniper/src/tests/query_tests.rs, juniper/src/tests/type_info_tests.rs, juniper/src/types/base.rs, juniper/src/value.rs
Fixes https://github.com/graphql-rust/juniper/issues/82
Note: I am new to Rust, please let me know if there is anything I can do better.
=> Preserve the order of requested fields

juniper/src/executor.rs, juniper/src/executor_tests/executor.rs, juniper/src/integrations/serde.rs, juniper/src/lib.rs, juniper/src/macros/object.rs, juniper/src/result_ext.rs, juniper/src/value.rs
An initial attempt at solving #69 and #40. It pretty much matches what I wrote here: https://github.com/graphql-rust/juniper/issues/40#issuecomment-320870842.
To ease construction of custom error objects, I built a small macro to construct `Value` instances from JSON syntax. This might be a bit out of place, in which case it can be removed from the PR. I also don't think it's going to be used for other purposes, but whatever :)
This obviously breaks all users of `.to_field_err` because of the renaming and places where you return `Err("string literal".to_owned())` from a field, but all instances of e.g. `let txn = executor.context().db.transaction()?` should continue to work.
=> Field error refactor

juniper/src/executor.rs, juniper/src/types/base.rs
`Executor` has a `push_error` method which is very useful for reporting
back errors. However, this method needs to know the location of the
error (`SourcePosition`). This commit adds a `location` method to the
executor.
=> Expose current executor's location

juniper/Cargo.toml, juniper/src/executor.rs, juniper/src/lib.rs, juniper/src/schema/model.rs
Changes `SchemaType` to use a `HashMap` backed by the [https://github.com/servo/rust-fnv](Fowler–Noll–Vo hash function). This hash function performs much better for smaller inputs (think short strings like most GraphQL type names) than the default hash function, SipHash. The downside is that it does not have the same cryptographic properties, which open it up to DoS vulnerabilities when the input can be manipulated from the outside.
In this change set, I have chosen to apply FNV only to the type and directive names tracked by the `SchemaType`, for two reasons:
1. Look-ups in `SchemaType::type_by_name` and co. have been showing up as the most frequent/expensive use of hashing for my workload.
2. I believe it is reasonable to assume that a malicious party would not have control over the …
=> perf(schema): use FnvHashMap for type and directive names

juniper/src/lib.rs, juniper_tests/Cargo.toml, juniper_tests/src/codegen/derive_enum.rs, juniper_tests/src/codegen/derive_input_object.rs, juniper_tests/src/codegen/derive_object.rs, juniper_tests/src/lib.rs
* Tests needed to be updated from `std::collections::HashMap` to `fnv::FnvHashMap` to match the `Registry` constructor
* Nightly only features needed to be removed for stable branches to pass in CI
=> Switched to FnvHashMap and removed nightly only features to fix failing tests

juniper/src/integrations/chrono.rs
I hit this error today, which I assume is related to https://github.com/graphql-rust/juniper/pull/78
```
POST /graphql application/json:
=> Matched: POST /graphql
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NameParseError("Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"DateTime<Utc>\" does not")', src/libcore/result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
1: std::sys_common::backtrace::_print
2: std::panicking::default_hook::{{closure}}
3: std::panicking::default_hook
4: std::panicking::rust_panic_with_hook
5: std::panicking::begin_panic
6: std::panicking::begin_panic_fmt
7: rust_begin_unwind
8: core::panicking::panic_fmt …
```
=> Give DateTime scalars valid names to pass validation

juniper/src/http.rs
This is just a useful thing for me because I need to clone the http request.
This shouldn't really influence anything else, every field already implements `Clone`
=> Derive Clone for GraphQLRequest

juniper/src/integrations/chrono.rs, juniper/src/integrations/mod.rs
I was having trouble getting my dates to parse, and realized it was because Z time zone was not being recognized. I changed it to use the built in "%+" format for parsing RFC3339 dates and added tests to check for this case.
=> Add support for Z time zone and fractional seconds in date formats

juniper/src/executor_tests/interfaces_unions.rs, juniper/src/validation/rules/fields_on_correct_type.rs
See http://graphql.org/learn/queries/#meta-fields.
Fixes https://github.com/graphql-rust/juniper/issues/112.
=> Support `__typename` for unions

juniper_rocket/Cargo.toml
Rocket requires nightly, but on nightly 2017-12-13 and after
the version juniper's integration was using wouldn't
build. This is solved by updating Rocket to `0.3.4` which
according to the [changelog](https://github.com/SergioBenitez/Rocket/blob/v0.3.4/CHANGELOG.md#version-034-dec-14-2017):
"Codegen was updated for 2017-12-13 nightly."
=> Update Rocket to latest version

juniper_rocket/Cargo.toml
`juniper_rocket` now requires nightly >= 2018-01-12. See
https://github.com/SergioBenitez/Rocket/issues/513#issuecomment-357407524.
Fixes https://github.com/graphql-rust/juniper/issues/125.
=> Update rocket in juniper_rocket to work with latest nightlies

juniper/src/types/base.rs
I ran into a case where Juniper was unwrapping a value and then placing it back into an Option.  It seems reasonable to just pass the Option up the call stack.
I've been playing with Juniper the last few weeks and it's really cool!  Thanks for building, maintaining and extending it!
=> Fixed case where .unwrap was being called instead of the Option just being propagated up the call chain

changelog/master.md, juniper_rocket/changelog/master.md
This makes it so people using git dependencies know what has changed. It also
gives a spot to make a running changelog so when we do a release we can just
copy and paste.
=> Add a master changelog

juniper_rocket/src/lib.rs
Cause of serde_json::to_string_pretty() is unefficient.
=> Change pretty json string to compact json string

juniper/src/value.rs
Without this change tests were failing to compile:
```
---- src/value.rs - graphql_value (line 196) stdout ----
error[E0468]: an `extern crate` loading macros must be at the crate root
--> src/value.rs:197:14
|
3 | #[macro_use] extern crate juniper;
|              ^^^^^^^^^^^^^^^^^^^^^
thread 'rustc' panicked at 'couldn't compile the test', librustdoc/test.rs:295:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
I also confirmed that `main` does not show up in the docs with
this change.
=> Make tests compile on latest nightly

juniper_iron/src/lib.rs
The warning was:
```
warning: unnecessary parentheses around function argument
--> juniper_iron/src/lib.rs:268:43
|
268 |             _ => return Ok(Response::with((status::MethodNotAllowed))),
|                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
|
= note: #[warn(unused_parens)] on by default
```
=> Fix warning in `iron_juniper`

juniper/src/executor_tests/executor.rs, juniper/src/types/base.rs
Currently, this:
```
query Query {
user {
... Fragment
}
}
fragment Fragment {
a
... on User {
b
}
}
```
returns
```
{
"user": {
"b": <value>
}
}
```
overriding the previous parallel fragment definition. This issue was fixed for pre-defined parallel fragments in https://github.com/graphql-rust/juniper/commit/c5552419780a8d4fccf5c34c5c24bc976829fd4e, the merge logic just hadn't been applied to inline fragments.
This adds that logic (a 1 line change) and adds a test.
=> Fix merging parallel inline fragments

juniper/src/integrations/chrono.rs
https://github.com/graphql-rust/juniper/issues/150
`NaiveDate` should serialize / deserialize from "2018-01-02" instead of a full ISO date.
=> Change serialization of Chronos NaiveDate

juniper/Cargo.toml, juniper/src/ast.rs, juniper/src/executor_tests/directives.rs, juniper/src/executor_tests/enums.rs, juniper/src/executor_tests/executor.rs, juniper/src/executor_tests/introspection/enums.rs, juniper/src/executor_tests/introspection/input_object.rs, juniper/src/executor_tests/variables.rs, juniper/src/integrations/serde.rs, juniper/src/lib.rs, juniper/src/macros/tests/field.rs, juniper/src/macros/tests/interface.rs, juniper/src/macros/tests/object.rs, juniper/src/macros/tests/scalar.rs, juniper/src/macros/tests/union.rs, juniper/src/parser/tests/value.rs, juniper/src/tests/type_info_tests.rs, juniper/src/types/base.rs, juniper/src/value.rs
`ordermap` changed names to `indexmap` and released a stable 1.0.
=> Switch to indexmap 1.0

juniper_rocket/Cargo.toml
Needed to bump minimum version to allow working on latest nightly.
=> (juniper_rocket) Bump minimum rocket version to 0.3.9

juniper/src/ast.rs, juniper/src/executor/mod.rs, juniper/src/executor_tests/introspection/input_object.rs, juniper/src/executor_tests/variables.rs, juniper/src/http/mod.rs, juniper/src/integrations/serde.rs, juniper/src/lib.rs, juniper/src/macros/scalar.rs, juniper/src/parser/document.rs, juniper/src/parser/lexer.rs, juniper/src/parser/parser.rs, juniper/src/parser/value.rs, juniper/src/schema/meta.rs, juniper/src/schema/model.rs, juniper/src/types/base.rs, juniper/src/types/name.rs, juniper/src/types/scalars.rs, juniper_iron/examples/iron_server.rs, juniper_iron/src/lib.rs
=> Clean up clippy warnings remove try!

juniper/src/executor/mod.rs, juniper/src/http/mod.rs, juniper_rocket/src/lib.rs
While using juniper with Rocket, I found the desire to create custom GraphQLResponses without having to call execute; specifically Rocket has a separate error handling flow that I want to allow to sometimes return normal GraphQLResponse errors.
This adds helpers to manually construct graphql responses with errors.
=> Add helpers to build custom GraphQLResponse

juniper_codegen/src/derive_input_object.rs
If a field has a description, we properly generate a meta field definition like:
```rust
{
let field = registry.field::<String>("id", &());
let field = field.description("Whatever");
field
}
```
If a field does not have a description, we were generating something like:
```rust
{
let field = registry.field::<String>("id", &());
let field = field; // <--- Note not needed
field
}
```
This of course works (and was likely optimized out by the compiler), but bloats
generated code for no benefit.
This change merely makes the second case generate:
```rust
{
let field = registry.field::<String>("id", &());
field
}
```
Fixes https://github.com/graphql-rust/juniper/issues/185.
=> Do not assign `field` to itself if no description specified when deriving input object

changelog/master.md, juniper_codegen/src/derive_enum.rs, juniper_codegen/src/derive_input_object.rs, juniper_codegen/src/derive_object.rs, juniper_codegen/src/util.rs, juniper_tests/Cargo.toml, juniper_tests/src/codegen/derive_enum.rs, juniper_tests/src/codegen/derive_input_object.rs, juniper_tests/src/codegen/derive_object.rs, juniper_tests/src/lib.rs
Fixes https://github.com/graphql-rust/juniper/issues/194.
=> Add support for using doc comments as descriptions

juniper_rocket/Cargo.toml
Even after doing `default-features = false` and cherry picking features on `juniper`, `juniper-rocket` was still pulling in default features.
This disables the default features on `juniper-rocket`.
=> Don't make assumptions what features the rocket app might use

juniper/src/integrations/serde.rs
Graphql spec requires every error contain `{"message": "field"}`. Every
error in juniper except ones fixed here are reported consistently with
this style. This commit fixes the representations of the three errors left.
While technically this commit can be treated as breaking, I think this issue is an oversight rather than intentional and should be fixed as a bug.
What do you think?
=> Consistent error serializing for GraphqlError

changelog/master.md, juniper/src/executor/mod.rs, juniper/src/executor_tests/executor.rs, juniper/src/lib.rs
Fixes #40.
This is not a breaking change, as `FieldResult` still works. For use cases which desire for custom error handling that return additional response fields ergnomically, those error types should implement `IntoFieldError` trait which converts your error type to the FieldError. This maintains that in the response, `message` field is always returned along with other optional user desired metadata.
You may implement your error as:
```
enum CustomError {
NotFound
}
impl IntoFieldError for CustomError {
fn into_field_error(self) -> FieldError {
FieldError::new("Not Found", graphql_value!({ "type": "NOT_FOUND" })
}
}
```
And use it likewise:
```
field add_likes(&executor, id: i32) -> Result<Like, CustomError> {
Err(CustomError::NotFound)
}
```
=> Allow custom errors to be returned from queries, mutations

juniper_iron/Cargo.toml, juniper_iron/src/lib.rs
It appears with newer 0.10.x hyper it no longer takes "{" or "}" in the
query string unescaped.
When I tried to set `juniper_iron` to an older hyper it complained that it
couldn't resolve due to `juniper_rocket` needing a newer version.
This was the path of least resistance. Note that we are still testing the same
thing, this change is needed as a consequence of how `iron_test` creates mock
requests.
Fixes https://github.com/graphql-rust/juniper/issues/206
=> Escape urls in iron integration tests

changelog/master.md, juniper/src/executor/look_ahead.rs, juniper/src/executor/mod.rs, juniper/src/executor_tests/executor.rs, juniper/src/http/mod.rs, juniper/src/integrations/serde.rs, juniper/src/lib.rs, juniper/src/parser/document.rs, juniper/src/parser/tests/document.rs, juniper/src/schema/schema.rs, juniper/src/types/pointers.rs, juniper/src/validation/mod.rs, juniper/src/validation/multi_visitor.rs, juniper/src/validation/rules/overlapping_fields_can_be_merged.rs, juniper/src/validation/traits.rs, juniper/src/validation/visitor.rs, juniper_codegen/src/derive_enum.rs, juniper_codegen/src/derive_input_object.rs, juniper_codegen/src/derive_object.rs, juniper_codegen/src/lib.rs, juniper_codegen/src/util.rs, juniper_iron/examples/iron_server.rs, juniper_iron/src/lib.rs, juniper_rocket/src/lib.rs, juniper_tests/src/codegen/derive_enum.rs, juniper_tests/src/codegen/derive_input_object.rs, juniper_tests/src/codegen/derive_object.rs
I don't see any reasons why GraphQLType is implemented for Box bot not implemented for Arc. Also added ToInputValue.
I don't add `FromInputValue` for same reason that serde is not implemented for `Rc` and `Arc` by default: one my expect same objects to be deserialized to the same Arc which isn't true. I'm not entirely sure of whether this precaution is still useful for graphql though.
=> Implement GraphQLType for Arc

juniper/src/executor_tests/directives.rs, juniper/src/executor_tests/enums.rs, juniper/src/executor_tests/introspection/enums.rs, juniper/src/executor_tests/introspection/input_object.rs, juniper/src/executor_tests/introspection/mod.rs, juniper/src/executor_tests/variables.rs, juniper/src/integrations/serde.rs, juniper/src/lib.rs, juniper/src/macros/tests/args.rs, juniper/src/macros/tests/field.rs, juniper/src/macros/tests/interface.rs, juniper/src/macros/tests/object.rs, juniper/src/macros/tests/scalar.rs, juniper/src/macros/tests/union.rs, juniper/src/parser/utils.rs, juniper/src/schema/model.rs, juniper/src/schema/schema.rs, juniper/src/tests/introspection_tests.rs, juniper/src/types/base.rs, juniper/src/types/containers.rs, juniper/src/value.rs, juniper_tests/src/codegen/derive_object.rs
* Replace the IndexMap in the serialized object with a plain
`Vec<(String, Value)>` because linear search is faster for few
elements
* Some general tweaks to skip some allocations
Addresses #199
=> Some performance improvements

changelog/master.md, juniper/src/executor/mod.rs, juniper/src/integrations/serde.rs, juniper/src/lib.rs
The June 2018 spec has reserved `extensions` as the field for error details. This PR updates the serializer to use this name.
From http://facebook.github.io/graphql/June2018/#sec-Errors:
> GraphQL may provide an additional entry to errors with key *extensions*. This entry, if set, must have a map as its value. This entry is reserved for implementors to add additional information to errors however they see fit, and there are no additional restrictions on its contents.
=> Use 'extensions' as field for error details

juniper/src/macros/scalar.rs, juniper/src/macros/tests/scalar.rs
Fixes https://github.com/graphql-rust/juniper/issues/227.
=> Allow crate type paths in `resolve` for `graphql_scalar!`

juniper_rocket/src/lib.rs, juniper_rocket/tests/custom_response_tests.rs
This PR exposes the fields of `GraphQLResponse` to make it easier to create custom responses.
Here we're building a custom Rocket response so we can set some `Access-Control-*` headers:
```rust
fn execute_graphql_request<'a>(
connection: DatabaseConnection,
request: GraphQLRequest,
) -> Response<'a> {
let context = Database::new(connection);
let schema = Schema::new(Query, Mutation);
// Prior to this change, this fails to compile with an error:
// "constructor is not visible here due to private fields".
let GraphQLResponse(status, json) = request.execute(&schema, &context);
Response::build()
.raw_header("Access-Control-Allow-Origin", "*")
.raw_header("Access-Control-Allow-Methods", "OPTIONS, GET, POST")
.raw_header("Access-Control-Allow-Headers", "Content-Type") …
```
=> [juniper_rocket] Expose GraphQLResponse fields

README.md
Hopefully the last README related fix 😉
=> Fix hyper examples link in README and remove trailing whitespace

juniper/src/executor_tests/variables.rs, juniper/src/validation/input_value.rs
Fixes https://github.com/graphql-rust/juniper/issues/242.
=> Handle InputValues that return `None`

README.md
I noticed on https://crates.io/crates/juniper that the logo is not rendering properly? I see the following warning:
`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/graphql-rust/juniper/blob/master/assets/logo/juniper-dark-word.png with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`
When I replace the URL with `raw` the logo appears.
=> Use raw url for Juniper logo in README

juniper_hyper/Cargo.toml, juniper_hyper/examples/hyper_server.rs, juniper_hyper/src/lib.rs
The previous implementation used a `futures_cpupool` for executing blocking juniper operations. This pool comes in addition to the thread pool started by hyper through tokio for executing hyper's futures. This patch uses [`tokio::blocking`](https://docs.rs/tokio-threadpool/0.1.7/tokio_threadpool/fn.blocking.html) to perform the blocking juniper operations while re-using the same thread pool as hyper, which simplifies the API.
=> Use only a single thread pool for juniper_hyper

.travis.yml, juniper_warp/Makefile.toml
Extracted out of https://github.com/graphql-rust/juniper/pull/251
=> Use latest cargo make

juniper/Cargo.toml
Updates uuid from 0.4 - 0.6 to 0.7. None of the breaking changes in 0.7 affect the codebase.
=> Update uuid to 0.7

juniper_warp/src/lib.rs
This is a more idiomatic name for warp, and it _is_ a filter.
=> Rename graphiql_handler to graphiql_filter in juniper_warp

juniper_warp/CHANGELOG.md, juniper_warp/Cargo.toml, juniper_warp/examples/warp_server/src/main.rs, juniper_warp/src/lib.rs
This unbreaks the build, as the newer warp deprecates some of the filters we
were using and we had `deny_warnings` on.
=> Upgrade `juniper_warp` to `warp` 0.1.8

changelog/master.md, juniper/src/executor/mod.rs, juniper/src/macros/common.rs, juniper/src/macros/interface.rs, juniper/src/macros/object.rs, juniper/src/macros/tests/args.rs, juniper/src/macros/tests/field.rs, juniper/src/schema/meta.rs, juniper/src/schema/schema.rs, juniper_codegen/src/derive_enum.rs, juniper_codegen/src/derive_object.rs, juniper_codegen/src/util.rs, juniper_tests/src/codegen/derive_input_object.rs
Follow on to https://github.com/graphql-rust/juniper/issues/194.
Updates the `GraphQLObject` and `GraphQLEnum` derives to use the first `#[deprecated]` annotation with a `note = ...` to supply the deprecation text, which can still be overridden with `#[graphql(deprecation = ...)]` like in https://github.com/graphql-rust/juniper/pull/195.
Additionally, this PR adds support for `#[doc = ...]` and `#[deprecated(note = ...)]` to the `graphql_object!` and `graphql_interface!` macros, which has some benefits:
* Lets your `field name(args...)` line-up so that they're easier to scan (even with a deprecation)`
* Allows mutliple doc strings be combined akin to the [collapse_docs](https://doc.rust-lang.org/rustdoc/the-doc-attribute.html) behavior.
(including any `const SOME_DESC: &'static str` if …
=> Infer graphql "deprecation" from #[deprecated(note = "...")] in derive (and macros)

.travis.yml, _build/azure-pipelines-template.yml
`cargo check --wasm32-unknown-unknown` is sufficient to demonstrate that the `juniper` and `juniper_codegen` crates can compile for WebAssembly, which should help avoid accidental regressions.
This is a small step towards the goals in #218.
=> Build wasm32-unknown-unknown in CI

juniper_rocket/CHANGELOG.md, juniper_rocket/Cargo.toml, juniper_rocket/examples/rocket_server.rs, juniper_rocket/src/lib.rs
Path handling changed in Rocket 0.4 and this commit updates the way
those paths are handled. It adds an implementation of the
`FromFormValue` trait to the `GraphQLRequest` object. It also changes
the documentation to use the multi-segement query string syntax.
All existing tests pass as expected.
Let me know if you have any questions or concerns!
=> Update juniper_rocket for Rocket 0.4-rc.1

juniper_rocket/README.md
It appears that the official repo was combined back into the main juniper repo, but the link didn't get updated.
=> Fix example link in juniper_rocket README

.travis.yml, _build/azure-pipelines-template.yml, juniper/CHANGELOG.md
Some dependiencies rely on cc, which after
https://github.com/alexcrichton/cc-rs/commit/228513449f3e2674cdce0f53206c9449af9d3778
requires 1.30.0.
=> Bump min rust version to 1.30.0

juniper/src/tests/introspection_tests.rs
* Prefix test function names with 'introspection'
* Use graphql_value! macro instead of manual construction
=> Clean up introspection tests

juniper/CHANGELOG.md, juniper/src/schema/model.rs, juniper/src/tests/introspection_tests.rs
The literal value according to the standard is INLINE_FRAGMENT,
not INLINE_SPREAD.
This oversight leads to invalid introspection schemas and trips up
third party tools.
Closes #305
=> Fix the literal value of DirectiveLocation::InlineFragment

azure-pipelines.yml
This was showing up as `check_formatting Job`, see https://dev.azure.com/graphql-rust/GraphQL%20Rust/_build/results?buildId=162
=> Fix Azure Pipelines formatting job display name

README.md, juniper/CHANGELOG.md, juniper/src/http/mod.rs, juniper/src/http/playground.rs, juniper_hyper/src/lib.rs, juniper_iron/CHANGELOG.md, juniper_iron/src/lib.rs, juniper_rocket/src/lib.rs, juniper_warp/src/lib.rs
This adds [GraphQL Playground](https://github.com/prisma/graphql-playground) integration, a much nicer and more powerful alternative to graphiql.
resolves #274
Notes:
* My nightly compiler panics, so I couldn't run (all) tests
* I did not add a top level alias because the one for graphiql [will be removed](https://github.com/graphql-rust/juniper/blob/29389e8f7231265dd4af398f17ad440cbefade55/juniper/src/lib.rs#L139)
* Contains no documentation or exaples, should I add some?
* I'd even propose to make this the default in the examples, since Playground is much nicer.
=> add GraphQL Playground integration

juniper/src/schema/meta.rs
The replacements were added in 1.30, which we have previously switched to
requiring. This silences two warnings.
=> Remove deprecated function calls

juniper_hyper/Makefile.toml
This will make the tests pass for now when dealing with pull requests.
Once merged we should create an issue to track the re-enabling of all channels (as an addition to the `TODO` comment).
=> Disable juniper_hyper testing due to rustc bug

juniper/CHANGELOG.md, juniper/src/value/object.rs
We have bumped past the point of this TODO so we can make
the changes.
=> Fix TODO for return type

docs/book/content/SUMMARY.md, docs/book/content/advanced/index.md, docs/book/content/advanced/introspection.md, docs/book/content/quickstart.md, docs/book/tests/build.rs, juniper/CHANGELOG.md, juniper/src/introspection/mod.rs, juniper/src/introspection/query.graphql, juniper/src/introspection/query_without_descriptions.graphql, juniper/src/lib.rs, juniper/src/tests/introspection_tests.rs, juniper/src/tests/mod.rs, juniper/src/tests/schema_introspection.rs
Fixes https://github.com/graphql-rust/juniper/issues/307.
I also fixed all the book tests to run and I am too lazy to put them in a different PR 🤷‍♂️
=> Add support for the canonical introspection query

juniper/src/executor/look_ahead.rs, juniper/src/executor/mod.rs
Fixes https://github.com/graphql-rust/juniper/issues/335
=> Support fragments with nested types in lookahead

docs/book/content/advanced/index.md, docs/book/content/schema/schemas_and_mutations.md, docs/book/content/servers/index.md, docs/book/content/servers/iron.md, docs/book/content/servers/official.md, docs/book/content/types/enums.md, docs/book/content/types/index.md, docs/book/content/types/input_objects.md, docs/book/content/types/objects/using_contexts.md, docs/book/content/types/other-index.md
This PR fixes many links on the documentation that were broken because they were not using the correct relative paths.
=> Fix broken docs links

juniper/src/tests/introspection_tests.rs, juniper/src/tests/schema_introspection.rs
With the new HashMap implementation, the maps on stable and nightly
have different ordering.
The introspection tests were relying on strict ordering.
This commit adds a simple sorting of the results to prevent
test failures.
A related discussion should be if we want to switch to index map for the types and directives, or just manually sort them for introspection queries, but this is the quick fix for now.
=> Make introspection tests ordering independent.

docs/book/content/servers/iron.md
This example doesn't work because we are not specifying the relative path for the graphql_object module.
=> Specify path to graphql_object module

juniper/CHANGELOG.md, juniper/src/http/mod.rs, juniper_rocket/CHANGELOG.md, juniper_rocket/src/lib.rs
> Measuring the runtime of queries will only tell if there are slow
> queries. To find out which queries are slow you need the operation name.
> 
> Getting the operation name was previously not possible from a Rocket
> request handler. This fixes that.
I ran into this issue recently when implementing performance performance
monitoring for an app using juniper-rocket.
=> Expose the operation name from `juniper_rocket::GraphQLRequest`

juniper/CHANGELOG.md, juniper/src/types/scalars.rs
This impl can cause weird runtime errors and serves
no real practical purpose.
Removing the impl is a breaking change but is the only
way to error out at runtime.
Closes #161.
=> Remove GraphQLType impl for unit () type

docs/book/content/types/scalars.md
This is now basically a requirement due to GraphQLObject derive
being generic.
Closes #358.
=> (book) Update the graphql_scalar! example to be generic

juniper/CHANGELOG.md, juniper/src/types/scalars.rs
As per the unofficial Rust API guidelines:
https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde
see #365
=> Implement Serialize/Deserialize for ID scalar

docs/book/content/servers/warp.md
This fix adds the correct link for the Warp Server example.
=> fix(docs): correct warp example link in book

juniper/src/macros/common.rs, juniper_codegen/src/derive_enum.rs, juniper_codegen/src/derive_input_object.rs, juniper_codegen/src/derive_object.rs, juniper_codegen/src/impl_object.rs, juniper_codegen/src/util.rs, juniper_hyper/src/lib.rs, juniper_warp/src/lib.rs
This is a minor code improvement.
Optimizes usages of `.expect()` and `.unwrap_or()` in non-test code to omit performing redudant operations if any.
=> Optimize .unwrap_or() and .expect() usages

docs/book/content/types/scalars.md, docs/book/tests/Cargo.toml, integration_tests/juniper_tests/src/codegen/derive_input_object.rs, integration_tests/juniper_tests/src/codegen/mod.rs, integration_tests/juniper_tests/src/codegen/scalar_value_transparent.rs, juniper/CHANGELOG.md, juniper_codegen/src/derive_scalar_value.rs, juniper_codegen/src/lib.rs
This commit implements a newtype style custom derive
for scalars via `#[derive(GraphQLScalarValue)]`, which now
supports both deriving a base enum scalar type and newtypes.
For newtypes, the `#[graphql(transparent)]` attribute is
required.
This commit:
* implements the derive
* adds integration tests
* updates the book
Closes #303
=> Implement newtype derive for scalars.

integration_tests/juniper_tests/src/issue_371.rs, integration_tests/juniper_tests/src/lib.rs, juniper/src/executor/look_ahead.rs, juniper/src/executor/mod.rs
Fixes https://github.com/graphql-rust/juniper/issues/371.
=> Fix lookahead when query contains multiple fields

README.md
This is kind of a shameless plug (I maintain juniper-from-schema) so feel free to close this if you don't want third-party libs mentioned in your readme.
However I think it might make sense to mention [juniper-from-schema](https://github.com/davidpdrsn/juniper-from-schema) in case people come to juniper expecting to find code generation features.
=> Mention juniper-from-schema in README

juniper/CHANGELOG.md, juniper/src/macros/tests/impl_object.rs, juniper_codegen/src/impl_object.rs
This commit forwards `mut` declaration of arguments in a #[juniper::object] macro invocation
to the generated code.
Closes #399
=> (codegen) Respect mut modifier on arguments in object proc macro

integration_tests/juniper_tests/src/issue_398.rs, integration_tests/juniper_tests/src/lib.rs, juniper/src/executor/mod.rs
Fixes https://github.com/graphql-rust/juniper/issues/398.
=> Don't assume lookaheads are always fields

juniper/src/types/async_await.rs, juniper_rocket/Cargo.toml, juniper_rocket/src/lib.rs
This updates juniper_rocket to support async Juniper & Rocket.  Async rocket is on a completely seperate branch just now, so had to pull that in.  I couldn't hide the futures-preview dependency behind a feature flag as Rocket hasn't put async behind a feature flag as far as I can see.
=> Update juniper_rocket for async.

juniper_codegen/Cargo.toml, juniper_codegen/src/util.rs
https://www.reddit.com/r/rust/comments/cz7u0j/psa_regex_13_permits_disabling_unicodeperformance/
The regex dependency is used in a single place, and it only validates ascii characters:
https://github.com/graphql-rust/juniper/blob/a3caf126b03533ea9b75b64056152500d38ce148/juniper_codegen/src/util.rs#L283
As such, we can drop the unicode support for faster compile times.
=> juniper_codegen: Drop regex & lazy_static dependencies

juniper/CHANGELOG.md, juniper/src/executor/look_ahead.rs
We're planning on using Juniper to power our API in the future, however we want to be able to dynamically compile our queries so that we can support a similar interface to our [existing ODATA solution](https://github.com/balena-io/pinejs/).  In order to support this we need to be able to visit the entire lookahead tree for an inbound query.
I've extended `LookAheadMethods` to add a few helper methods, the most important of which is the `child_names` method, which means that we're able to use it to iterate the children of each node.
I've also added `name` to `LookAheadArgument` for the same reason.
=> Improve visitability of lookahead types.

examples/warp_async/Cargo.toml, examples/warp_async/src/main.rs, integration_tests/async_await/Cargo.toml, integration_tests/async_await/src/main.rs, juniper/Cargo.toml, juniper/src/lib.rs, juniper_benchmarks/Cargo.toml, juniper_benchmarks/src/lib.rs, juniper_rocket/Cargo.toml, juniper_rocket/src/lib.rs, juniper_warp/Cargo.toml, juniper_warp/src/lib.rs
This PR upgrades `futures-preview` and `tokio` crates to its latest alpha versions. And removes using `#![feature(async_await)]`.
=> Upgrade futures-preview and tokio crates

juniper/src/parser/parser.rs, juniper/src/parser/tests/document.rs, juniper/src/parser/value.rs
=> Bubble up scalar error

juniper_codegen/src/impl_object.rs
Due to changes in name resolving logic in `#[juniper::object]` macro name attribute is not resolved correctly. This PR reverts name resolving logic to the one present in `master` branch.
When running certain queries (for example, introspection query) some types are not found by juniper, though they should exist. Consider the following example:
```graphql
query {
__type(name: "User") {
...FullType
}
}
fragment FullType on __Type {
kind
name
description
}
```
Server returns `"Unknown type \"__Type\"` error. High-level resolving logic:
```
got request ->
started validation ->
query has correct syntax ->
type "__Type" not found ->
-> return error
```
Type `__Type` is declared in `TypeType` impl block in `src/schema/schema.rs`:
```rust
#[crate::object_internal(
name = "__Type"   // <-- type …
```
=> Fix name resolving error in `#[juniper::object]`

integration_tests/juniper_tests/src/codegen/derive_object_with_raw_idents.rs, integration_tests/juniper_tests/src/codegen/mod.rs, juniper/CHANGELOG.md, juniper_codegen/src/derive_input_object.rs, juniper_codegen/src/lib.rs, juniper_codegen/src/util.rs
If you have a schema like
```rust
#[juniper::object]
impl Query {
fn r#type(r#fn: MyInputType) -> Vec<String> {
unimplemented!()
}
}
#[derive(GraphQLInputObject, Debug, PartialEq)]
struct MyInputType {
r#trait: String,
}
```
The names in the GraphQL schema would still include `r#`. This patch fixes that for field names on fields of types, fields of input types, and arguments. Any other places where this should be fixed?
I discovered this while working on https://github.com/davidpdrsn/juniper-from-schema/pull/93.
=> Handle raw identifiers

examples/warp_async/Cargo.toml, integration_tests/async_await/Cargo.toml, juniper/Cargo.toml, juniper/src/macros/scalar.rs, juniper_benchmarks/Cargo.toml, juniper_codegen/src/derive_enum.rs, juniper_codegen/src/util.rs, juniper_rocket/Cargo.toml, juniper_rocket/src/lib.rs, juniper_warp/Cargo.toml
Rebase `async-await` onto futures 0.3.1:
- Use futures 0.3.1 in all packages except `juniper_warp` (warp supports futures 0.3 only on git)
- Replace all `futures::future::BoxFuture` with `juniper::BoxFuture` in macros
=> Use futures 0.3.1 in async-await

docs/book/content/quickstart.md
Got the error
```
error[E0433]: failed to resolve: could not find `object` in `juniper`
--> server/src/main.rs:20:12
|
20 | #[juniper::object(
|            ^^^^^^ could not find `object` in `juniper`
```
due to the wrong version mentioned in the quickstart docs. This should fix it!
=> docs(quickstart): Fix juniper version so the examples work

juniper/Cargo.toml
The `uuid` maintainers have started releasing in the `0.8` version train.  I've relaxed the version requirements on `juniper`'s dependencies to allow juniper users to specify a different version in their `Cargo.toml` and still have the integration work.
=> Loosen constraints on uuid version.

juniper/src/http/graphiql.rs
incl. upgrade to latest React
Note: `cdn.jsdelivr.net` is used as CDN server, since `cdnjs.cloudflare.com` does not provide latest version of `graphiql`.
=> Use latest graphiql (v0.17.2)

juniper/src/validation/rules/no_unused_variables.rs
Was copied from undefined variable error message.
=> Small fix/typo: unused variable error message

docs/book/content/types/objects/complex_fields.md
Adding a small note in doc to avoid confusion about `impl` block for complex fields.
See #482
=> Add note on complex fields impl block in doc

juniper/src/value/mod.rs
To find out how to construct a `null` value in `graphql_value` you have to look at the implementation of the macro. With the hope to help others find out quicker how it's done this PR adds another line to the doc of the function
=> Add example of how to construct null in graphql_value

juniper/CHANGELOG.md, juniper/src/executor/mod.rs, juniper/src/executor_tests/executor.rs, juniper/src/executor_tests/variables.rs, juniper/src/lib.rs, juniper/src/validation/input_value.rs
Fix for #455 
This PR changes a larger number of files than expected. Here is the rationale.
* We want to validate input variables only for the operation selected for execution. The code that extracts the selected operation was already present in `execute_validated_query`. However, we need the result in `validate_input_values` which is called before `execute_validated_query`.
* So, I extracted the code to a `get_operation` method (the naming mimics the GraphQL spec, see https://graphql.github.io/graphql-spec/June2018/#GetOperation() ), meant to be called directly from `execute`. The resulting Operation can be then passed directly to `validate_input_values` instead of the whole document.
* However, the `get_operation` code originally runs after the validation of the document, but …
=> Validate variables of the executed operation only

juniper/src/types/pointers.rs, juniper/src/types/scalars.rs
I'm building a GraphQL API using Juniper that proxies another GraphQL
API.  It does a large fetch upfront from the underlying GraphQL API,
transforms it into a different format and then implements some
resolvers that do some further filtering.
One of these resolvers ends up looking like:
```
async fn items(&self, ...) -> Vec<Item> {
self.items.iter().filter(...).collect()
}
```
This causes us problems as we're returning owned Item's and Item is a
large nested structure that would be expensive to clone.
Our current work around was to put Item into an Arc, as Arc is
comparatively cheap to clone.  So our method becomes:
```
async fn items(&self, ...) -> Vec<Arc<Item>> {
self.items.iter().filter(...).map(Arc::clone).collect()
}
```
However to support this we needed Arc to implement …
=> Implement GraphQLTypeAsync for Arc

docs/book/content/quickstart.md, docs/book/content/types/objects/complex_fields.md, juniper/CHANGELOG.md, juniper/Cargo.toml, juniper/release.toml, juniper/src/executor/mod.rs, juniper/src/executor_tests/executor.rs, juniper/src/executor_tests/variables.rs, juniper/src/http/graphiql.rs, juniper/src/http/playground.rs, juniper/src/lib.rs, juniper/src/validation/input_value.rs, juniper/src/validation/rules/no_unused_variables.rs, juniper/src/value/mod.rs, juniper_codegen/Cargo.toml, juniper_codegen/src/lib.rs, juniper_hyper/CHANGELOG.md, juniper_hyper/Cargo.toml, juniper_iron/CHANGELOG.md, juniper_iron/Cargo.toml, juniper_rocket/CHANGELOG.md, juniper_rocket/Cargo.toml, juniper_warp/CHANGELOG.md, juniper_warp/Cargo.toml
Attempt at rebase of async-await branch on to master. One test fails.
=> Master to async await

integration_tests/juniper_tests/src/codegen/derive_enum.rs, integration_tests/juniper_tests/src/codegen/derive_object.rs, integration_tests/juniper_tests/src/codegen/derive_object_with_raw_idents.rs, integration_tests/juniper_tests/src/codegen/impl_union.rs, integration_tests/juniper_tests/src/codegen/scalar_value_transparent.rs, integration_tests/juniper_tests/src/custom_scalar.rs, integration_tests/juniper_tests/src/issue_371.rs, integration_tests/juniper_tests/src/issue_398.rs, juniper/src/macros/scalar.rs, juniper/src/types/scalars.rs
There is still some weirdness going on. Running async and
non-async tests in `integration_tests/*` works, but running it
from `integration_tests` does not.
Possibly fixes https://github.com/graphql-rust/juniper/issues/506.
=> Fix scalar and some tests under async

docs/book/tests/Cargo.toml, juniper/Cargo.toml
Fixes #494
This PR upgrades `uuid` to `0.8` version.
=> Upgrade uuid to 0.8 version

docs/book/tests/Cargo.toml, integration_tests/async_await/Cargo.toml, integration_tests/juniper_tests/Cargo.toml, juniper/Cargo.toml, juniper_benchmarks/Cargo.toml, juniper_codegen/Cargo.toml, juniper_rocket_async/Cargo.toml, juniper_warp/Cargo.toml
This PR specifies `futures` dependency crate version as [carret requirement](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements) (`0.3.1`) instead of fixed version (`=0.3.1`) to allow downstream crates naturally upgrade to new `futures` crate version as the want and accordingly to semver.
=> Use caret requirement for specifying 'futures' crate version

juniper_rocket/CHANGELOG.md, juniper_rocket/Cargo.toml, juniper_rocket/src/lib.rs, juniper_rocket_async/CHANGELOG.md, juniper_rocket_async/Cargo.toml, juniper_rocket_async/src/lib.rs
Rocket integration does not use any of the `default-features` on Rocket, but does not specify `default-features = false`.
This prevents users from using crates that depend on newer version of `ring` library than that which `private-cookies` crate of `Rocket` uses.
=> Rocket / Skip Default Features

docs/book/content/SUMMARY.md, docs/book/content/advanced/dataloaders.md, docs/book/content/advanced/index.md
This PR is intended to address #444 
I had a similar problem to the issue author finding a decent explanation/example of using data loaders with juniper, and so want to give an example to make it easier for others.
Happy to make any changes from nitpicks to overhauls, cull some or explain more :grin: 
@MIkailBag feedback would be appreciated if you can spare the time!
=> WIP: Add dataloader explaination to book

.github/workflows/book.yml, .github/workflows/ci.yml
Adds two workflows based on the Travis and Azure setup.
I haven't looked into the Codecov stuff whether an additional secret is required for the CI workflow
or how it could be possible to use the [Codecov Action][codecov].
The Book workflows requires a `ACTION_DEPLOY_KEY` secret for deployment to GitHub Pages.
See [`peaceiris/actions-gh-pages#1-add-ssh-deploy-key`][gh-pages] for the configuration.
The `secrets.GITHUB_TOKEN` token wouldn't trigger a page rebuild.
I don't know what's wrong with the [macOS nightly] run.
related to: #453 
[macOS nightly]: https://github.com/nickelc/juniper/runs/355009442#step:7:1583
[codecov]: https://github.com/marketplace/actions/codecov
[gh-pages]: https://github.com/peaceiris/actions-gh-pages#1-add-ssh-deploy-key
=> Add GitHub workflows for CI and Book

juniper_codegen/Cargo.toml
Fixes https://github.com/graphql-rust/juniper/issues/534.
I am not sure if the best way is to have folks bring their own futures for the
derives / macros or to pull it in as a dep explicitly like I have done here.
Because people are filing issues, we will do it this way and see what other issues arise.
=> Add futures dependency

docs/book/content/types/interfaces.md
These aren't reimplemnted yet as proc macros. Disabling them
so book tests on PRs pass and the website is updated.
=> Temporarily disable interface tests

docs/book/content/servers/index.md, docs/book/content/servers/official.md
The lists of official server integrations don't match the reading order in which their corresponding pages appear in the book. This can cause the user to unknowingly skip a section of the book by clicking on the links.
Make the server integrations order match the reading order from the book.
Fixes #547
=> Match the list of integrations to the page order

docs/book/content/types/objects/complex_fields.md
There's a comment [here](https://docs.rs/juniper/0.14.2/juniper/attr.object.html) that only GraphQL fields can be specified in `#[juniper::object]` impl block, yet in the book it was not specified, I needed help to get the idea of separating my `new` method in another impl block.
I simply copied that information in the book because it feels important; one would not know of this only by reading the book.
=> Warning about normal methods in juniper::object impl blocks

juniper/src/executor_tests/executor.rs, juniper/src/types/async_await.rs
The ordering was off when run under async. Not 100% sure I understand this code but this seems
to work.
=> Fix `field_execution` and `merge_parallel_inline_fragments` async tests

docs/book/content/servers/third-party.md
...since I've stopped the development both of `tsukuyomi` and `finchers` a few months ago.
=> doc: remove outdated examples from third-party integrations list

.github/workflows/ci.yml
there is a github action called davidB/rust-cargo-make which downloads a prebuild cargo-make for you.
You can decide not to specify the version, in which case the latest prebuilt version is downloaded, or provide it a version.
**I haven't test it**, but i see this action is used in many projects so it might reduce your need to maintain some shell and powerscript files to implement that and make the workflow simpler.
I kept it with cargo-make 0.20.0 as you have today, but there a lot of new features from 0.20 and some have to do specifically with workspaces.
so you might want to try to drop or change that value.
you can see more info on the github action here: https://github.com/marketplace/actions/rust-cargo-make
=> Use github action to download cargo-make

juniper/src/http/mod.rs
It's useful to print a debug message after `execute` of its result
=> Add debug derive to GraphQLResponse

integration_tests/async_await/src/main.rs, juniper/src/lib.rs
Added the validation of operations before executing then, i found that the validation was missing and because of that a panic was ocurring in the request of a subscription.
Before submitting a PR, you should follow these steps to prevent redundant churn or CI failures:
=> Added document validation in the resolve_into_stream method and a test

juniper/CHANGELOG.md, juniper/src/http/graphiql.rs, juniper_hyper/CHANGELOG.md, juniper_hyper/examples/hyper_server.rs, juniper_hyper/src/lib.rs, juniper_iron/CHANGELOG.md, juniper_iron/examples/iron_server.rs, juniper_iron/src/lib.rs, juniper_rocket/CHANGELOG.md, juniper_rocket/examples/rocket_server.rs, juniper_rocket/src/lib.rs, juniper_rocket_async/src/lib.rs, juniper_warp/CHANGELOG.md, juniper_warp/examples/warp_server.rs, juniper_warp/src/lib.rs
Addresses #501
I didn't find a place where this type of stuff is tested. Please let me know if I need to add another test somewhere.
There are a few breaking changes:
BREAKING CHANGE: `juniper::http::graphiql::graphiql_source` now requires
a second parameter
BREAKING CHANGE: `juniper_hyper::graphiql` now requires
a second parameter
BREAKING CHANGE: `juniper_iron::GraphiQLHandler::new` now requires
a second parameter
BREAKING CHANGE: `juniper_rocket::graphiql_source` now requires
a second parameter
BREAKING CHANGE: `juniper_warp::graphiql_filter` now requires
a second parameter
Here is a gif of it working adapting the example in `examples/warp_subscriptions/src/main.rs`.
This was done by adding the following lines to `examples/warp_subscriptions/src/main.rs`:
```
.or(warp::get() …
```
=> Add subscriptions support on GraphiQL

docs/book/content/types/unions.md, integration_tests/juniper_tests/src/codegen/derive_union.rs, integration_tests/juniper_tests/src/codegen/mod.rs, juniper/CHANGELOG.md, juniper/src/lib.rs, juniper_codegen/src/derive_union.rs, juniper_codegen/src/lib.rs, juniper_codegen/src/util/mod.rs
Implements derive macros for tagged enums which are translated into GraphQLUnion types. The following features are provided
- The macro implements GraphQLAsyncType. 
- If all variants of the tagged enum have different types, then the derive macro implements `std::convert::From<T>`  converter for these types.
Fixes: https://github.com/graphql-rust/juniper/issues/586
=> Derive macro for tagged enums (GraphQLUnion)

juniper/Cargo.toml, juniper/src/http/mod.rs, juniper/src/integrations/serde.rs, juniper/src/types/scalars.rs, juniper_actix/Cargo.toml, juniper_actix/src/lib.rs, juniper_hyper/Cargo.toml, juniper_iron/Cargo.toml, juniper_iron/examples/iron_server.rs, juniper_rocket/Cargo.toml, juniper_rocket_async/Cargo.toml, juniper_warp/Cargo.toml
Another minor code improvement to remove direct usages of `serde_derive` crate (which is available via `derive` feature of `serde` crate).
Also, removes unnecessary `serde` deps in `Cargo.toml` of integration crates.
=> Remove direct usage of `serde_derive` crate

juniper/src/http/mod.rs
Fixes #639
This PR disallows to deserialize `GraphQLBatchRequest` with empty `Vec`  inside.
=> Disallow deserialize empty GraphQLBatchRequest (#639)

juniper/src/parser/lexer.rs, juniper/src/parser/tests/lexer.rs
Without this fix the panic looks like the following:
```rust
---- parser::tests::lexer::string_errors stdout ----
thread 'parser::tests::lexer::string_errors' panicked at 'byte index 4 is not a char boundary; it is inside 'ɠ' (bytes 3..5) of `"\uɠ^A`', src/libcore/str/mod.rs:2219:5
```
This was found via fuzzing with `cargo-fuzz`.
=> Fix panic with invalid unicode query

Cargo.toml
Tiny fix required in order to get the basic_subscriptions example to run.
=> Exclude basic subscriptions example from workspace

juniper/CHANGELOG.md, juniper/src/http/mod.rs, juniper_actix/src/lib.rs, juniper_hyper/CHANGELOG.md, juniper_hyper/src/lib.rs, juniper_iron/CHANGELOG.md, juniper_iron/src/lib.rs, juniper_rocket/CHANGELOG.md, juniper_rocket/src/lib.rs, juniper_rocket_async/CHANGELOG.md, juniper_rocket_async/src/lib.rs, juniper_warp/CHANGELOG.md, juniper_warp/Cargo.toml, juniper_warp/src/lib.rs
Fixes #426  
Extends #442
This PR is majorly based on @sd2k's work in #442 and adds support of `Content-Type: application/graphql` POST requests to all integration crates.
Also, some refactorings are made across codebase for better readability, and removing redudant boxing here and there.
- rename `HTTPIntegration` as `HttpIntegration`;
- rename `post` as `post_json` method;
- add `post_graphql` method.
- At the moment it deserializes request's body as JSON, which is not correct.
- Return `400 Bad Request` if `Content-Type` is absent or invalid.
- Return `400 Bad Request` if `Content-Type` is absent or invalid.
- Forward request if `Content-Type` is absent or invalid.
- Forward request if `Content-Type` is absent or invalid.
- Omit executing request if `Content-Type` is absent or invalid.
=> Support "Content-Type: application/graphql" (#426)

docs/book/content/advanced/dataloaders.md
Hello! I was using this recently so I thought of updating the docs.
This PR is intended to update the code example provided in the book (#518) to a newer version of the dataloader.
I also copied a bit of the explanation given in https://github.com/graphql/dataloader and created another PR to update the example repository https://github.com/jayy-lmao/rust-graphql-docker/pull/5
Let me know if this is useful or if I need to change anything.
=> Update dataloader explanation code

juniper/CHANGELOG.md, juniper/src/executor/look_ahead.rs
Add a method to access the children of look ahead structs
Make the behaviour around accessing aliased lookahead fields more consistent
=> Improve lookahead visibility for aliased fields

juniper/src/types/scalars.rs
For EmptyMutation and EmptySubscription. The built-in derive
expects `T: Default`, which is not necessary for a PhantomData
wrapper.
=> Relax Default impl constraint

README.md, docs/book/content/quickstart.md, docs/book/content/schema/schemas_and_mutations.md, juniper/CHANGELOG.md, juniper/Cargo.toml, juniper/src/schema/meta.rs, juniper/src/schema/mod.rs, juniper/src/schema/model.rs, juniper/src/schema/translate/graphql_parser.rs, juniper/src/schema/translate/mod.rs
This PR brings support for the GraphQL Schema Language using `graphql_parser`, continuing on the work in the PR by @arlyon.
This PR supersedes #324 and #624.
=> Add support for GraphQL Schema Language 

juniper/src/http/mod.rs, juniper_subscriptions/Cargo.toml, juniper_subscriptions/src/lib.rs, juniper_warp/src/lib.rs
This is a small refactoring to cut off redundant stuff, which complicates downstream implementations.
=> Relax redundant 'static lifetime bounds on ScalarValue in juniper_subscriptions::Coordinator

juniper/src/util.rs, juniper_codegen/src/util/mod.rs
Rust (and clippy) advocate prefixing unused vars with an underscore. If doing that with juniper,
the expectation (at least personally) is that the variable name won't change. With the current
`to_camel_case` code a leading underscore capitalises. This prevents that by checking for and removing
it.
This is potentially (but unlikely) breaking. Anyone who _does_ have things with a leading underscore can simply capitalise the var to get the same effect, which is enough for me to call it a bug.
Some more discussion is in https://github.com/graphql-rust/juniper/issues/623
There was a similar (unmerged) PR for a different graphql project here: graphql-python/graphene#492 that had the same thought process.
=> Update to_camel_case to respect the rust convention of prefixing '_'

docs/book/content/types/objects/complex_fields.md
Just something I noticed while giving the docs a read :)
=> chore(docs): fix typo in complex fields section

juniper_rocket_async/Cargo.toml, juniper_rocket_async/src/lib.rs
The `async` branch has now landed on Rocket's `master`. The git
branch has been deleted.
=> Update to latest Rocket on `master`

integration_tests/juniper_tests/src/custom_scalar.rs, juniper_codegen/src/util/mod.rs
This makes the `graphql_subscription` macro work with custom scalars and adds a test.
=> Fix subscriptions with custom scalars

juniper_warp/src/lib.rs
* Previously, the `juniper_warp` crate would not even compile with the "subscriptions" feature due to a missing `use anyhow::anyhow`. This PR adds that.
* The `context` argument to `graphql_subscriptions` previously required `Clone`. That was unnecessary and made the function unusable with perfectly valid context types. This PR just removes that constraint.
* Previously, as soon as a subscription was stopped, the "got_close_signal" boolean would be set, and the WebSocket connection would be rendered unusable. This meant that multiple subscriptions on a single WebSocket connection were completely broken (and worse yet, completely silent). This PR adds a `HashMap` of subscription states (currently just an atomic boolean) to make it possible to stop subscriptions without interrupting others …
=> Fix juniper_warp subscriptions

juniper_warp/src/lib.rs
It's possible that I don't understand the original reasoning behind commit 54be035 removing `.clone()` here but this PR adding it back allows compilation to succeed and completes the fix of #705 via #707 for me. With this change multiple subscriptions now work on master.
=> Add clone() back to request_id to fix compiler error in juniper_warp

juniper_rocket_async/src/lib.rs
This commit changed where `Outcome` is exported:
https://github.com/SergioBenitez/Rocket/commit/adc79016cdfe732a6c095dd96aa5286a70c4d3be
=> Unbreak integration with latest rocket master

juniper_warp/src/lib.rs
Content-Type header checks shouldn't be done with `exact_ignore_case`, as this breaks for clients using additional parameters. The fix is simple: remove the filter. `body::json()` performs the correct Content-Type check for us.
This also makes the tests a little harder by adding the charset parameter.
=> Fix for warp content type filter

juniper/src/lib.rs, juniper/src/types/subscriptions.rs, juniper_subscriptions/src/lib.rs, juniper_warp/src/lib.rs
Previously `SubscriptionConnection` was a stream of `GraphQLResponse<'a, S>`, a newtype for:
```rust
Result<(Value<S>, Vec<ExecutionError<S>>), GraphQLError<'a>>
```
This doesn't really make much sense because subscription events cannot have any sort of pre-execution errors and the `GraphQLResponse` is always `Ok`. This is a bit misleading and complicates lifetimes as the output of the stream can otherwise be `'static`.
This PR just makes `SubscriptionConnection` a stream of unwrapped tuples. This has the added benefit of allowing the user of the API to actually access the data / errors before serializing. Alternatively, it might make sense to create a new type for this, e.g. an `ExecutionResult` type.
This is something I came across while working on #709 that I figured could go in its …
=> Simplify SubscriptionConnection

Cargo.toml, examples/warp_subscriptions/Cargo.toml, examples/warp_subscriptions/src/main.rs, juniper/release.toml, juniper_graphql_ws/CHANGELOG.md, juniper_graphql_ws/Cargo.toml, juniper_graphql_ws/Makefile.toml, juniper_graphql_ws/release.toml, juniper_graphql_ws/src/client_message.rs, juniper_graphql_ws/src/lib.rs, juniper_graphql_ws/src/schema.rs, juniper_graphql_ws/src/server_message.rs, juniper_subscriptions/src/lib.rs, juniper_warp/Cargo.toml, juniper_warp/src/lib.rs
This add a new crate: `juniper_graphql_ws`. This crate implements the [Apollo graphql-ws protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md).
This is a replacement for the implementation that was previously in `juniper_warp`. A few of the differences:
* ~Simplifies `SubscriptionConnection`. There is a dedicated PR for this here: https://github.com/graphql-rust/juniper/pull/719. This can be reviewed separately, or that PR can be closed and everything can just be reviewed at once.~ (Edit: This was merged separately.)
* Errors are now correctly emitted for field resolution errors within subscription event streams. Previously they were just being silently dropped inside of `juniper_subscriptions::whole_responses_stream`. This and the first bullet are …
=> GraphQL-WS crate and Warp subscriptions update

juniper_graphql_ws/src/server_message.rs
Closes https://github.com/graphql-rust/juniper/issues/729.
=> omit empty error vec in data message serialization

juniper_graphql_ws/CHANGELOG.md, juniper_graphql_ws/src/client_message.rs, juniper_graphql_ws/src/lib.rs, juniper_graphql_ws/src/utils.rs
=> fix(juniper_graphql_ws): correct null deserialization issue

examples/actix_subscriptions/Cargo.toml, examples/actix_subscriptions/src/main.rs, juniper/Cargo.toml, juniper/src/http/mod.rs, juniper/src/lib.rs, juniper/src/tests/fixtures/starwars/schema.rs, juniper_actix/Cargo.toml, juniper_actix/src/lib.rs, juniper_hyper/Cargo.toml, juniper_iron/Cargo.toml, juniper_rocket/Cargo.toml, juniper_rocket_async/Cargo.toml, juniper_warp/Cargo.toml
A tiny subscriptions tests framework. 
An array of messages (to be sent or to be expected) is created and then given to the runner. This should work nicely with any web server. An example can be found below.
```rust
async fn test_ws_simple_subscription<T: WsIntegration>(integration: &T) {
let messages = vec![
WsIntegrationMessage::Send(
r#"{
"type":"connection_init",
"payload":{}
}"#
.to_owned(),
),
WsIntegrationMessage::Expect(
r#"{
"type":"connection_ack"
}"#
.to_owned(),
WS_INTEGRATION_EXPECT_DEFAULT_TIMEOUT,
),
WsIntegrationMessage::Expect(
r#"{
"type":"ka"
}"#
.to_owned(),
WS_INTEGRATION_EXPECT_DEFAULT_TIMEOUT,
),
WsIntegrationMessage::Send(
r#"{
"id":"1",
"type":"start",
"payload":{
"variables":{},
"extensions":{},
"operationName":null,
"query":"subscription { asyncHuman { id, name, …
```
=> Actix subscriptions tests

juniper_hyper/examples/hyper_server.rs
Turns out these aren't necessary.
=> Remove unnecessary moves

juniper/Cargo.toml, juniper_codegen/Cargo.toml
`juniper` brings **a lot** of weight and compilation times into my projects and this PR is an attempt to decrease this burden.
Local tests say that `cargo build/check/test` will now have ~8 less crates to download and the used technique can be further extended into other projects (juniper_actix, juniper_warp, etc) to decrease CI times.
=> Remove unused dependencies

juniper/src/executor/look_ahead.rs
Revealed from #682  
The `LookAheadSelection` and `ConcreteLookAheadSelection` are mostly reference types: part of their data is a reference to some outer value.
The current `LookAheadMethods` trait (which abstracts public interface to these two selections) cannot express this notion, however. This result in the situation:
```bash
let name: &'static str = "my_string";
let executor: Executor<'static, _> = Executor::create_from(&name);  // just imitating
let field_name: &'static str = executor.look_ahead().field_name();  // fails to compile
```
Compilation fails because `field_name` has the lifetime of a temporary value, returned by `executor.look_ahead()` (which acts as a reference in this case). This happens because `LookAheadMethods::field_name` bounds returned value to the `&self` …
=> Fix LookAheadMethods lifetimes

juniper_graphql_ws/src/lib.rs
=> Reduce warp_subscriptions example to 15 seconds so that GQL clients don't disconnect

juniper_graphql_ws/src/lib.rs
Just noticed https://github.com/graphql-rust/juniper/pull/756. The docs need to be updated to match.
=> Update graphql-ws keep-alive docs

juniper/src/types/scalars.rs
Fixes #775 
Allows to parse `f64` scalar from integers.
=> Fix parsing f64 from Scalar::Int

integration_tests/juniper_tests/src/codegen/derive_enum.rs, integration_tests/juniper_tests/src/codegen/derive_input_object.rs, integration_tests/juniper_tests/src/codegen/derive_object.rs, juniper_codegen/src/derive_enum.rs, juniper_codegen/src/derive_input_object.rs, juniper_codegen/src/derive_object.rs, juniper_codegen/src/impl_object.rs, juniper_codegen/src/util/mod.rs
Add a new attribute `rename` which could be "none", "camelCase", "SCREAMING_SNAKE_CASE".
By default (when this attribute is not specified) the exiting rules apply: camelCase to structs, SCREAMING_SNAKE_CASE to enums.
Inspired by Serde & Structopts.
This does not change interfaces because I haven't figured how to do them yet.
Re https://github.com/graphql-rust/juniper/issues/201.
=> Allow disabling case convertion

docs/book/content/SUMMARY.md, docs/book/content/advanced/implicit_and_explicit_null.md, docs/book/content/advanced/index.md, integration_tests/juniper_tests/src/explicit_null.rs, integration_tests/juniper_tests/src/lib.rs, juniper/CHANGELOG.md, juniper/src/ast.rs, juniper/src/lib.rs, juniper/src/types/base.rs, juniper/src/types/mod.rs, juniper/src/types/nullable.rs, juniper_codegen/src/impl_object.rs, juniper_codegen/src/util/mod.rs
This adds the ability to distinguish between implicit and explicit null. This closes https://github.com/graphql-rust/juniper/issues/183.
The changes to Juniper to support this are pretty simple:
* `FromInputValue` now provides a `from_implicit_null` method. By default this just invokes `from_input_value(&InputValue::<S>::Null)` like Juniper did before, but types can provide their own implementation if they have a different representation for implicit nulls.
* `Arguments` no longer inserts `InputValue::Null`s into itself for missing arguments. This means `Arguments::get` will later return `None` for implicitly null arguments.
* Codegen has been modified to invoke `from_implicit_null` when arguments or fields are absent.
And finally, to make this functionality convenient for anyone to use …
=> Add ability to distinguish between implicit and explicit null

integration_tests/juniper_tests/src/infallible_as_field_error.rs, integration_tests/juniper_tests/src/lib.rs, juniper/CHANGELOG.md, juniper/src/executor/mod.rs
Makes it possible to use `Result<T, Infallible>` as your return type from resolvers, which can be handy sometimes.
=> Implement `IntoFieldError` for `Infallible`

integration_tests/juniper_tests/src/issue_500.rs, integration_tests/juniper_tests/src/lib.rs, juniper/CHANGELOG.md, juniper/src/executor/look_ahead.rs, juniper/src/executor/mod.rs
A fix for the panic that occurs when you try to call `executor.look_ahead()` on a nested fragment spread. Includes a test that has 3 levels of fragment nesting, to make sure the issue is gone.
=> Fix #500 (crash from look_ahead on nested fragments)

docs/book/content/types/interfaces.md, docs/book/content/types/unions.md, integration_tests/codegen_fail/fail/interface/downcast_method_conflicts_with_external_downcast_fn.rs, integration_tests/codegen_fail/fail/interface/downcast_method_conflicts_with_external_downcast_fn.stderr, integration_tests/codegen_fail/fail/interface/downcast_method_wrong_input_args.rs, integration_tests/codegen_fail/fail/interface/downcast_method_wrong_return_type.rs, integration_tests/codegen_fail/fail/interface/fields_duplicate.rs, integration_tests/codegen_fail/fail/union/trait_method_conflicts_with_external_resolver_fn.stderr, integration_tests/codegen_fail/fail/union/trait_with_attr_on_method.rs, integration_tests/codegen_fail/fail/union/trait_with_attr_on_method.stderr, integration_tests/juniper_tests/src/codegen/interface_attr.rs, integration_tests/juniper_tests/src/codegen/union_attr.rs, juniper/src/executor_tests/interfaces_unions.rs, juniper/src/executor_tests/mod.rs, juniper/src/macros/tests/field.rs, juniper/src/macros/tests/object.rs, juniper/src/tests/fixtures/starwars/schema.rs, juniper_codegen/src/graphql_interface/attr.rs, juniper_codegen/src/graphql_interface/mod.rs, juniper_codegen/src/graphql_union/attr.rs, juniper_codegen/src/lib.rs
This PR corrects the naming of attributes in `#[graphql_interface]` and `#[graphql_union]` macros, placed on fields and field arguments to apply well along with the `#[graphql_object]` macro.
See https://github.com/graphql-rust/juniper/issues/737#issuecomment-727015731:
> ```rust
> #[graphql_object]
> impl Object {
>     #[graphql(name = "fancy")]
>     fn fancy_field() -> i32 { 0 }
> }
> 
> #[graphql_interface]
> trait Interface {
>     #[graphql_interface(name = "fancy")]  // <-- should be renamed as `#[graphql]`
>     fn fancy_field() -> i32 { 0 }
> }
> ```
Also, revives some tests in `juniper` crate, previously commented and skipped.
=> Fix attributes naming on methods and arguments for interfaces and unions

integration_tests/juniper_tests/src/codegen/derive_scalar.rs, integration_tests/juniper_tests/src/codegen/mod.rs, juniper/CHANGELOG.md, juniper_codegen/src/derive_scalar_value.rs
Currently it is not possible to use scalar values with custom scalars. The following code fails.
```rust
#[derive(juniper::GraphQLScalarValue)]
pub struct LargeId(i64);
```
In order to allow custom scalars, scalars values must allow to set a different scalar value. Currently the implementation only uses generics. The following snippet works with this PR. Notice that `MyScalarValue` is a scalar implementation including the `i64` data type.
```rust
#[derive(juniper::GraphQLScalarValue)]
#[graphql(Scalar = MyScalarValue)]
pub struct LargeId(i64);
```
=> Allow different Scalar for GraphQLScalarValue

integration_tests/juniper_tests/src/codegen/impl_object.rs, juniper/src/macros/tests/args.rs, juniper_codegen/src/util/mod.rs
Fixes #786.
This pull request allows raw identifiers to be used for field arguments, and updates `multi_args_descr_trailing_comma` to include a trailing comma.
=> Allow raw identifier for field arguments

juniper/src/schema/schema.rs, juniper/src/tests/query_tests.rs, juniper/src/types/async_await.rs, juniper/src/types/base.rs
Fixes #815
Note that I was completely unfamiliar with the code and am still unsure if this is the proper way to solve the problem. It works for me. Let me know if I have to change more stuff, if I should fix the bug at a different place in code or whether I should change anything else.
Thanks!
=> Apply type condition in inline fragments to fix panic when using inline fragments with interfaces

integration_tests/juniper_tests/src/arc_fields.rs, integration_tests/juniper_tests/src/lib.rs, juniper/src/types/marker.rs, juniper/src/types/pointers.rs
We've just updated a service we work with to the latest release of
juniper (it's been on a fairly old master commit for some time).  In
this service we have some fields that are contained within `Arc`s, which
I added support for in #479.
Since then it seems the new marker traits of `IsInputType` &
`IsOutputType` have been added, but they do not support `Arc`, leading
to:
```
error[E0277]: the trait bound `Arc<menu::Menu>: IsOutputType<__S>` is not satisfied
--> src/graphql.rs:36:1
|
36 | #[juniper::graphql_object(Context=Context)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `IsOutputType<__S>` is not implemented for `Arc<menu::Menu>`
|
= note: required by `juniper::marker::IsOutputType::mark`
= note: this error originates in an attribute macro (in Nightly builds, run with -Z …
```
=> Mark `Arc` with `IsInputType` & `IsOutputType`.

_build/release.toml, juniper/release.toml, juniper_codegen/release.toml, juniper_graphql_ws/Makefile.toml, juniper_graphql_ws/release.toml, juniper_hyper/release.toml, juniper_iron/release.toml, juniper_rocket/release.toml, juniper_rocket_async/release.toml, juniper_subscriptions/Makefile.toml, juniper_subscriptions/release.toml, juniper_warp/release.toml
Some crates need to rewrite values when they are released in other crates. It turns out, by default we use a general config `_build/release.toml`. So it turns out these local-to-the-crate `release.toml`s were not being used unless explicitly chosen in the local-to-the-crate `Makefile.toml`. This removes the dead `release.toml`s and overrides the ones that need to edit other crates on release.
=> Fix release replacements.

docs/book/content/quickstart.md
Seems like the example code in the quickstart guide is missing an use declaration. 
The code fails to compile: `error: cannot find macro `graphql_value` in this scope` with `rustc 1.48.0 (7eac88abb 2020-11-16)`
=> Add missing use declaration in Quickstart

juniper_rocket_async/src/lib.rs
rocket async has recently bumped its tokio dependency
to 1.0.1 which breaks juniper_rocket_async. This can
be trivially fixed by using rocket's tokio re-export.
=> juniper_rocket_async: fix tokio dependency

juniper/src/http/playground.rs
the linked file on jsDelivr doesn't work, as I detailed in this issue on the GraphQL Playground repo (https://github.com/graphql/graphql-playground/issues/1310). Going back to version 1.7.26 ensures the playground loads for now until they can publish a new version with a working middleware.js file.
(not working) link to the currently used 1.7.27 file:
https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.27/build/static/js/middleware.js
fixed link to the 1.7.26 file:
https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.26/build/static/js/middleware.js
=> Use working GraphQL Playground version

examples/basic_subscriptions/Cargo.toml, examples/warp_async/Cargo.toml, juniper_codegen/Cargo.toml, juniper_codegen/src/common/parse/mod.rs
syn 1.0.60 has updated it's `Type::__Nonexhaustive` to
`Type::TestExhaustive`, breaking juniper.  This updates juniper to use
the recommended idiom for doing exhaustive matching on `Type`, which
fixes this.
Not entirely clear if this needs exhaustive matching or if we could
just use a fallback, but this fixes the build at least.
I imagine this will break for users who are still on an old syn though.
Fixes #858
=> Update juniper_codegen for syn 1.0.60

juniper_rocket_async/examples/rocket_server.rs, juniper_rocket_async/src/lib.rs
Add support for subscriptions for GraphiQL and Playground in `juniper_rocket_async`.
Note this changes the function signatures. Since the crate hasn't been release I'm not sure about backwards compatibility concerns. At least the signatures are consistent now.
=> Support subscriptions for GraphiQL and Playground.

README.md, docs/book/content/README.md, docs/book/content/servers/iron.md, juniper/src/lib.rs
The iron project has lost control of the ironframework[dot]io domain and it is apparently now serving malicious content: https://github.com/iron/iron/issues/632
This updates the iron URL to point to the GitHub repo instead.
=> Update iron link

juniper/Cargo.toml, juniper/src/executor/mod.rs, juniper/src/parser/lexer.rs, juniper/src/schema/meta.rs, juniper/src/schema/schema.rs
Replaced name of field with a `smartstring` instead of `String`. Running `cargo bench --features expose-test-schema` indicates a slight improvement on the `query_type_name` test and slightly lower performance on the `introspection_query` test. Here is an example of two runs:
**Master**:
test introspection_query ... bench:     962,848 ns/iter (+/- 70,973)
test query_type_name     ... bench:      11,557 ns/iter (+/- 894)
**This PR/branch**:
test introspection_query ... bench:     978,076 ns/iter (+/- 70,523)
test query_type_name     ... bench:      11,354 ns/iter (+/- 1,471)
=> Use smartstring for name of field (#819).

juniper/CHANGELOG.md, juniper/src/executor/look_ahead.rs
- Issues with removing them documented in issue #878
=> Un-deprecate the select_child, has_child, and child_names methods

juniper_hyper/examples/hyper_server.rs, juniper_hyper/src/lib.rs
Fix https://github.com/graphql-rust/juniper/issues/881.
Changes juniper_hyper to return `Response<Body>` instead of `Result<Response<Body>, hyper::Error>` for:
* `graphql`
* `graphql_sync`
* `graphiql`
* `playground`
Feel free to let me know if I'm missing any others!
=> Make juniper_hyper functions return `Response<Body>` where applicable

integration_tests/juniper_tests/src/issue_407.rs, integration_tests/juniper_tests/src/lib.rs, juniper/src/types/async_await.rs, juniper/src/types/base.rs
=> Fragment spreads in Interface types

integration_tests/juniper_tests/Cargo.toml, integration_tests/juniper_tests/src/lib.rs, integration_tests/juniper_tests/src/pre_parse.rs, juniper/src/ast.rs, juniper/src/executor/look_ahead.rs, juniper/src/executor/mod.rs, juniper/src/lib.rs, juniper/src/schema/meta.rs, juniper/src/validation/input_value.rs, juniper/src/validation/mod.rs, juniper/src/validation/multi_visitor.rs, juniper/src/validation/rules/mod.rs
Making these APIs public is based on my understanding of https://github.com/graphql-rust/juniper/pull/773#issuecomment-703783048 and https://github.com/graphql-rust/juniper/pull/773#issuecomment-704009918
This PR is related to #776, #726, and enables features similar to #843 to be implemented in user land code. In my project I'm currently doing this (pseudo code) in the first step:
``` rust
fn compile() {
let document = parse_document_source(document_source, &root_node.schema)?;
visit_all_rules(&mut ctx, &document);
let operation = get_operation(&document, operation_name)?;
Ok((document.clone(), operation.clone()))
}
```
so I can make use of the `operation` and `document` and then in the second step I'm using the [now public] `validation::validate_input_values` and …
=> Make the executor and validation APIs public to enable split parsing and execution

integration_tests/juniper_tests/src/issue_914.rs, integration_tests/juniper_tests/src/lib.rs, juniper/src/value/object.rs
Closes #914 
This fixes the issue raised and adds a test to prevent future regressions.
Note that this slightly changes to public api of `juniper::Object`'s: `add_field` will now check if a new field exists and is an object, and in that case merge the objects keys instead of replacing the old object.
It might also make sense to not return anything from that function (which is a breaking change of the public interface, but seems to compile without modification to the existing uses in the juniper crate, I think the behavior was originally copied from `std::collections::HashMap`).
=> Fixes Issue 914

juniper_rocket_async/Cargo.toml, juniper_rocket_async/src/lib.rs
The `tokio` dependency is only required for tests and should have been in the `dev-dependencies` section in `Cargo.toml`.
Since `rocket` already ships with a async test annotation `tokio` can be removed completely.
=> Eliminate tokio dependency in juniper_rocket_async

integration_tests/juniper_tests/src/issue_925.rs, integration_tests/juniper_tests/src/lib.rs, juniper_codegen/src/util/mod.rs
Closes #925 
Using sync code block for wrapping user defined code was causing `?` to short circuit the whole outer async block, which does not return a user defined error but `FieldError` itself.    
So user defined errors were implicitly converted into `FieldError`'s via `std::convert::Into`, the default implementation of which does not set `FieldError::extensions` at all.
=> Fix subscription error extensions (#925)

juniper/CHANGELOG.md, juniper/src/schema/model.rs
The `as_schema_language` and `as_parser_document` methods are currently only implemented when `QueryT::TypeInfo = ()` (and the same for `MutationT` and `SubscriptionT`). This requirement is superfluous, so we can just move these methods to the other `impl` block that doesn't have these constraints on `TypeInfo`.
=> Don't require `()` TypeInfo for schema language methods

juniper_rocket_async/Cargo.toml, juniper_rocket_async/src/lib.rs
From now on `dependabot` will take care of bumping rocket to a newer release.
=> juniper_rocket_async: bump to 0.5.0-rc.1

integration_tests/juniper_tests/src/issue_945.rs, integration_tests/juniper_tests/src/lib.rs, juniper/CHANGELOG.md, juniper/src/types/async_await.rs, juniper/src/types/base.rs, juniper_rocket_async/src/lib.rs
closes #945 
See the included test for an example repro of this panic. I haven't spent enough time to fully grok the flow of the code here, so please let me know if I'm pulling the wrong lever and accidentally fixing the issue.
=> Fixes panic when spreading untyped union fragment.

juniper_codegen/src/util/mod.rs
Fully qualify `std::result::Result` such that it doesn't collide with locally defined type aliases for `Result`. This improves macro hygiene.
=> juniper_codegen: macro hygiene for graphql_subscription

Makefile.toml, RELEASING.md, juniper/Makefile.toml, juniper_codegen/Makefile.toml, juniper_graphql_ws/Makefile.toml, juniper_subscriptions/Makefile.toml
This is much better as we can hardocde the crates to filter out in
one place, can selectively release certain crates easily,
and only have one command instead of the "-some" hack
=> Switch releasing commands from a blocklist to an allowlist

integration_tests/juniper_tests/src/issue_798.rs, integration_tests/juniper_tests/src/lib.rs, juniper/CHANGELOG.md, juniper/src/tests/subscriptions.rs, juniper/src/types/async_await.rs, juniper/src/types/base.rs
Fixes #798 
Allows to resolve interface fragments on union types by checking whether the concrete resolved type is a subtype of the specified fragment type.
=> Allow resolving interface fragments on unions (#798)

juniper_rocket/CHANGELOG.md, juniper_rocket/src/lib.rs
Fixes #930
For all `juniper_*` integrations makes `juniper::GraphQLBatchRequest` accessible from newtype wrappers.
=> Provide access for integration GraphQLRequest wrappers to its inner types (#930)

docs/book/content/advanced/dataloaders.md, examples/actix_subscriptions/Cargo.toml, juniper_actix/Cargo.toml, juniper_actix/src/lib.rs
This PR updates `actix-web` and related crates betas and fixes conflict on [`#[test]` macro](https://github.com/actix/actix-web/blob/master/CHANGES.md#added-1).
=> Update actix-web beta

README.md
A few of the book links were 404'ing and this PR updates them. Please let me know if the updates I have made are not intended.
=> Update book links to fix 404

docs/book/content/servers/hyper.md, docs/book/content/servers/iron.md, docs/book/content/servers/rocket.md, docs/book/content/servers/warp.md
Simple update to latest versions of `juniper` and `juniper_$SERVER` versions referenced in the server integration docs, as current versions are stale.
=> Update versions referenced in server integration docs

juniper/CHANGELOG.md, juniper/src/validation/rules/overlapping_fields_can_be_merged.rs
This is a potential denial-of-service attack vector. Thanks to
[@quapka](https://github.com/quapka) for the detailed vulnerability report
and reproduction steps.
=> Fix panic on malformed queries with recursive fragments.

juniper_rocket/CHANGELOG.md, juniper_rocket/src/lib.rs
Before, it was not possible to set a different request body size limit. Now, the configurable limit value from Rocket's `Limits` struct [1] is obtained with a fallback to the hardcoded value in case no value has been configured.
[1] https://api.rocket.rs/master/rocket/data/struct.Limits.html
I'm running into the hardcoded limit now and therefore would really appreciate if a release of juniper_rocket could be made after this has been merged.
=> juniper_rocket: make request limit configurable

juniper/Cargo.toml, juniper/src/integrations/bson.rs
- Enable `serde/std` feature flag for `juniper` crate;
- Mark `bson` integration unit tests that uses `chrono` with `#[cfg(chrono)]`.
- Created PR:
- Before merge:
=> Fix build with `default-features = false`

book/src/types/scalars.md, juniper/CHANGELOG.md, juniper/src/executor/mod.rs, juniper/src/http/mod.rs, juniper/src/integrations/serde.rs, juniper/src/lib.rs, juniper/src/parser/document.rs, juniper/src/parser/parser.rs, juniper/src/parser/tests/document.rs, juniper/src/parser/value.rs, juniper/src/schema/meta.rs, juniper/src/types/scalars.rs, juniper/src/value/scalar.rs, juniper_codegen/src/graphql_scalar/mod.rs, juniper_codegen/src/lib.rs, juniper_graphql_ws/src/lib.rs, juniper_graphql_ws/src/server_message.rs, juniper_subscriptions/src/lib.rs, tests/integration/src/codegen/scalar_attr_derive_input.rs, tests/integration/src/codegen/scalar_attr_type_alias.rs, tests/integration/src/codegen/scalar_derive.rs, tests/integration/src/custom_scalar.rs, tests/integration/src/lib.rs
The lifetime specifier `'a` in `GraphQLError` bubbles up to `http::GraphQLBatchResponse`, `http::GraphQLResponse` and every other caller. This lifetime makes working with responses unergonomical. Issue #528 describes the problem as 
> "This is way too much insight into the inner workings of juniper than should exist on a public error -- I just need a nice message if there's a problem parsing, not the whole token. "
- Changed `GraphQLError::ParseError(Spanning<ParseError<'a>>)` to `GraphQLError::ParseError(String)` ([see here](https://github.com/graphql-rust/juniper/pull/1081/files#diff-918477c8ee99971edb5f7fae9233759174d9315a9991cfa4ef6c4437a288837eL99))
- Removed lifetime `'a` from `GraphQLError`, all its parents and callers.
=> Remove lifetime 'a from GraphQLError (#528)

juniper/CHANGELOG.md, juniper/src/types/utilities.rs, juniper/src/validation/rules/arguments_of_correct_type.rs, juniper/src/validation/test_harness.rs
Addresses https://github.com/graphql-rust/juniper/issues/1085
Explicit `null` values are not being accepted for nullable list parameters. This change causes explicit `null`s (as well as variables) to be accepted. Also adds tests for `null` values being provided for both nullable and non-nullable lists.
=> Accept explicit null argument for nullable list parameter

juniper/Cargo.toml, tests/integration/Cargo.toml
By default chrono uses time 0.1.44, which has a vulnerability:
https://rustsec.org/advisories/RUSTSEC-2020-0071
chrono 0.4.20 does not depend on the vulnerable parts of the time 0.1.x
versions, see https://github.com/chronotope/chrono/releases/tag/v0.4.20
This change is to satisfy simple dependency scanners.
=> Remove indirect time 0.1.44 dependency by chrono

juniper_hyper/CHANGELOG.md, juniper_hyper/examples/hyper_server.rs, juniper_hyper/src/lib.rs
All responses were created from strings anyway (via `Body::from`), but `String` implements the `Body` trait directly. With this change, it is easy to inspect the response body, which is not true for `Body`.
Fixes #1096
=> Change body type of `juniper-hyper` functions from `Body` to `String`

.github/workflows/ci.yml, Makefile, juniper/Cargo.toml, juniper/README.md, juniper/release.toml, juniper_actix/Cargo.toml, juniper_actix/README.md, juniper_actix/release.toml, juniper_codegen/Cargo.toml, juniper_codegen/README.md, juniper_codegen/release.toml, juniper_graphql_ws/Cargo.toml, juniper_graphql_ws/README.md, juniper_graphql_ws/release.toml, juniper_hyper/Cargo.toml, juniper_hyper/README.md, juniper_hyper/release.toml, juniper_iron/Cargo.toml, juniper_iron/README.md, juniper_iron/release.toml, juniper_rocket/Cargo.toml, juniper_rocket/README.md, juniper_rocket/release.toml, juniper_subscriptions/Cargo.toml, juniper_subscriptions/README.md, juniper_subscriptions/release.toml, juniper_warp/Cargo.toml, juniper_warp/README.md, juniper_warp/release.toml, release.toml
This PR improves/updates CI pipeline and project toolchain.
=> Improve CI

juniper/src/parser/lexer.rs, juniper/src/types/name.rs
This fixes some Clippy issues and simplifies some things.
=> is_ascii_xxx clippy fixes

README.md
The link "https://gitter.im/juniper-graphql" responds with a 404. It appears that the link should be updated to "https://gitter.im/juniper-graphql/Lobby".
=> Update Gitter link in README.md

juniper_actix/CHANGELOG.md, juniper_hyper/src/lib.rs
Resolves #1169
See https://github.com/graphql-rust/juniper/issues/1169#issue-1726260032
> **Describe the bug** The code block
> 
> https://github.com/graphql-rust/juniper/blob/a648dd727519991c2e3c762af16eac027b2acec2/juniper_hyper/src/lib.rs#L225-L229
> 
> seems to be missing a statement where operation_name would be set to `Some(value)`.
> 
> **To Reproduce** Steps to reproduce the behavior: Just read through code. See the variable is defined a `None` and nowhere is being set.
Set the missing `operation_name`, as suggested.
=> Fix `operation_name` not being set in `juniper_hyper` (#1169)

.github/dependabot.yml, Makefile, examples/warp_subscriptions/Cargo.toml, examples/warp_subscriptions/src/main.rs, juniper/.gitignore, juniper/CHANGELOG.md, juniper/Cargo.toml, juniper/Makefile, juniper/package.json, juniper/src/http/graphiql.html, juniper/src/http/graphiql.js, juniper/src/http/graphiql.rs, juniper_actix/src/lib.rs, juniper_warp/src/lib.rs
Extends #1069
See https://github.com/graphql-rust/juniper/pull/1069#issuecomment-1138685047:
> GraphiQL and GraphQL Playground updates go fully unnoticed for us. I think it's time do to something about it.
> 
> It would be nice to add a `package.json` manifest to the repository with a versions range of GraphiQL and GraphQL Playground (along with the `yarn.lock` file), where in the `post-install` stage we copy the sources of GraphiQL/GraphQL Playground to `juniper/src/` dir, and in the code we use `include_str!()` at the propriate places.
> 
> Finally, we make dependabot to look after GraphiQL/GraphQL Playground updates for us.
Introduces `package.json` which tracks `graphiql` versions, and a simple toolchain downloading and adopting actual integration files.
Updates …
=> Upgrade GraphiQL to 3.0.5 version (#1069)

juniper_codegen/src/common/deprecation.rs, juniper_codegen/src/common/field/arg.rs, juniper_codegen/src/common/field/mod.rs, juniper_codegen/src/common/gen.rs, juniper_codegen/src/graphql_enum/mod.rs, juniper_codegen/src/graphql_input_object/mod.rs, juniper_codegen/src/graphql_interface/mod.rs, juniper_codegen/src/graphql_object/mod.rs, juniper_codegen/src/graphql_scalar/mod.rs, juniper_codegen/src/graphql_subscription/mod.rs, juniper_codegen/src/graphql_union/derive.rs, juniper_codegen/src/graphql_union/mod.rs, juniper_codegen/src/scalar_value/mod.rs, tests/codegen/pass/local_results.rs, tests/codegen/pass/local_send.rs, tests/codegen/src/lib.rs
If user code has a type alias (or custom type) called `Result` or `Option` etc,
this would be used instead of the intended standard library types causing
surprising compile errors from generated code.
Using the fully qualified path allows the generated code to be isolated
from user types.
Fixes #1194
=> Use fully qualified path to types in generated code

juniper/src/http/mod.rs, juniper_actix/CHANGELOG.md, juniper_actix/Cargo.toml, juniper_actix/src/lib.rs, juniper_graphql_ws/CHANGELOG.md, juniper_graphql_ws/src/graphql_transport_ws/mod.rs, juniper_warp/src/lib.rs
Follows #1191, #1186
See https://github.com/graphql-rust/juniper/issues/1186#issuecomment-1730323445:
> 2. Reimplement `juniper_actix::subscritions` via actorless `actix-ws` crate instead of the current `actix-web-actors::ws` one. The whole thing with actors cooperates very badly with `juniper_graphql_ws` state machine, introducing too excessive polling, which leads to panics and abnormal WebSocket closures instead of normal ones. It also gives a feeling of fighting with actors, trying to pair them with `Stream`/`Sink`, instead of easing it. So, the actorless `actix-ws` crate should go just fine, as we have in the `juniper_warp` crate.
Also, WebSocket connections are not closed normally in `juniper_actix`, due to panics:
Get rid of `actix-web-actors::ws`  and use  `actix-ws` crate …
=> Use `actix-ws` for `juniper_actix` subscriptions 

juniper/CHANGELOG.md, juniper/src/executor/look_ahead.rs
Depending on how the trait will be used in the future this might not be a good idear.
Another possibility would be to return `impl Iterator<Item=&Self>` this is already possible in nightly and was stablized two weeks ago https://github.com/rust-lang/rust/pull/115822
=> Avoid an unecessary clone in `LookAheadMethods::children`

.github/workflows/ci.yml, juniper/CHANGELOG.md, juniper/Cargo.toml, juniper/src/integrations/anyhow.rs, juniper/src/integrations/mod.rs, tests/integration/tests/codegen_object_attr.rs
Resolves #988
See #988: 
> [anyhow](https://github.com/dtolnay/anyhow) is a dominant error handling library for rust. Currently, there is no convenient way to use anyhow `Err`s in juniper code. For example,
> 
> ```
> struct Mutation;
> 
> #[juniper::graphql_object]
> impl Mutation {
>   async fn Foo(line_number: i32) -> FieldResult<bool> {
>     anyhow::ensure!(line_number >= 0);
>     Ok(true)
>   }
> }
> ```
> 
> doesn't work.
> 
> [IntoFieldResult](https://docs.rs/juniper/0.15.7/juniper/trait.IntoFieldResult.html) offers a way of translating custom error types into `FieldResult`s, but unfortunately implementing `IntoFieldResult` for `anyhow::Error` is not possible due to https://doc.rust-lang.org/error-index.html#E0117.
Provide `IntoFieldError` implementation for `anyhow::Error` …
=> Support `anyhow::Error` (#988)

juniper/CHANGELOG.md, juniper/src/executor/mod.rs, juniper/src/http/mod.rs, juniper/src/lib.rs, juniper/src/parser/lexer.rs, juniper/src/parser/parser.rs, juniper/src/validation/context.rs
Resolves #103 
Provides `Clone` and `PartialEq` implementations for a `GraphQLResponse`, so it can be tossed around.
=> Implement `Clone` and `PartialEq` for `GraphQLResponse` (#103)

juniper/Cargo.toml, juniper/src/types/async_await.rs
`auto_enums` is from the same author as `futures-enum` ([taiki-e](https://github.com/taiki-e)), and `auto_enums` appears more up-to-date. But the most important thing is that this gets rid of `syn 1` from juniper's non-dev dependencies.
=> refactor: Use auto_enums instead of futures-enum

juniper/src/validation/multi_visitor.rs, juniper/src/validation/rules/no_fragment_cycles.rs, juniper/src/validation/rules/no_undefined_variables.rs, juniper/src/validation/rules/no_unused_fragments.rs, juniper/src/validation/rules/unique_input_field_names.rs, juniper/src/validation/rules/variables_in_allowed_position.rs, juniper/src/validation/traits.rs, juniper/src/validation/visitor.rs
As mentioned in https://github.com/graphql-rust/juniper/pull/1209#discussion_r1388107123, making `Spanning` generic over `Sp` allows avoiding copying 6 `usize`s (the `Span`) in places where a borrowed Spanning needs to be type mapped. I.e. the `Document` contains `Spanning<InputValue>`, but `InputValue` is an enum, so when the spanned item's type gets mapped into a reference to each variant, there's no need to transform `&Spanning<T, Span>` to `Spanning<&U, Span>`. It can instead be transformed to a `Spanning<&U, &Span>`.
This applies to the `Visitor` trait and its methods related to the visitation of `InputValue`s. The `Visitor` trait is public, but `#[doc(hidden)]`.
=> refactor: Avoid copying Span when evaluating rules

.github/workflows/ci.yml, README.md, book/src/introduction.md, book/src/types/scalars.md, juniper/CHANGELOG.md, juniper/Cargo.toml, juniper/README.md, juniper/src/integrations/jiff.rs, juniper/src/integrations/mod.rs
This adds [Jiff](https://crates.io/crates/jiff) integration, behind feature flag `jiff`, for the following date/time types:
- [`civil::Date`](https://docs.rs/jiff/latest/jiff/civil/struct.Date.html) to GraphQL scalar [`LocalDate`](https://the-guild.dev/graphql/scalars/docs/scalars/local-date)
- [`civil::Time`](https://docs.rs/jiff/latest/jiff/civil/struct.Time.html) to GraphQL scalar [`LocalTime`](https://the-guild.dev/graphql/scalars/docs/scalars/local-time)
- [`civil::DateTime`](https://docs.rs/jiff/latest/jiff/civil/struct.DateTime.html) to GraphQL scalar [`LocalDateTime`](https://the-guild.dev/graphql/scalars/docs/scalars/local-date-time)
- [`Timestamp`](https://docs.rs/jiff/latest/jiff/struct.Timestamp.html) to GraphQL scalar …
=> Add integration for Jiff date/time types

book/src/types/scalars.md, juniper/CHANGELOG.md, juniper/Cargo.toml, juniper/src/executor_tests/interfaces_unions.rs, juniper/src/executor_tests/introspection/mod.rs, juniper/src/integrations/bson.rs, juniper/src/integrations/chrono.rs, juniper/src/integrations/chrono_tz.rs, juniper/src/integrations/jiff.rs, juniper/src/integrations/time.rs, juniper/src/integrations/url.rs, juniper/src/integrations/uuid.rs
https://graphql-scalars.dev/docs/scalars collection added `LocalDate`, `LocalDateTime`, `URL` and `UUID` scalars.
We need to make our Scalars named that way compliant with them.
=> Correct scalars complience

.github/workflows/ci.yml, book/src/types/scalars.md, juniper/CHANGELOG.md, juniper/Cargo.toml, juniper/src/integrations/jiff.rs
This is a follow-up to #1271 and adds integration for the following [Jiff](https://crates.io/crates/jiff) date/time types:
- [`Zoned`](https://docs.rs/jiff/latest/jiff/struct.Zoned.html) to GraphQL scalar `ZonedDateTime`[^1]
- [`tz::TimeZone`](https://docs.rs/jiff/latest/jiff/tz/struct.TimeZone.html) to GraphQL scalar `TimeZoneOrUtcOffset`[^2], and to GraphQL scalar [`TimeZone`](https://the-guild.dev/graphql/scalars/docs/scalars/time-zone) with a newtype
- [`tz::Offset`](https://docs.rs/jiff/latest/jiff/tz/struct.Offset.html) to GraphQL scalar [`UtcOffset`](https://the-guild.dev/graphql/scalars/docs/scalars/utc-offset)
[^1]: This GraphQL scalar is not documented at https://graphql-scalars.dev but we can introduce it here as laid out in …
=> Add Jiff date/time types `Zoned`/`TimeZone`

.github/workflows/ci.yml, juniper_axum/Cargo.toml
Removes the transitive dependency on `mio`. This allows projects targeting `wasm32-unknown-unknown` to compile. Fixes #1282.
The `mio` dependency is being brought in via: `juniper_axum`→`axum`→`axum/tokio`→`tokio/net`→`mio`. By disabling the default features of `axum`, we disable its `tokio` feature.
[`axum`'s comment on `mio`](https://github.com/tokio-rs/axum/blob/main/examples/simple-router-wasm/src/main.rs#L10-L12):
> [`mio`](https://docs.rs/mio/latest/mio/index.html), tokio's IO layer, does not support the  `wasm32-unknown-unknown` target which is why this crate requires `default-features = false` for axum.
1. Install the "wasm32-unknown-unknown" target
`rustup target add wasm32-unknown-unknown`
2. Create a dummy WASM library
`cargo install cargo-generate && cargo generate --git …
=> Remove transitive dependency on `mio`

.github/workflows/ci.yml, juniper_hyper/CHANGELOG.md, juniper_hyper/Cargo.toml, juniper_hyper/README.md, juniper_hyper/src/lib.rs
Should resolve #1102 
> ## Problem
> Attempts to use any other hyper request type aside `Request<hyper::body::Incoming>` fails with a compile-time error of type mismatch
> ## Solution
> Add generic support for valid supported hyper `Request` or any custom `Request` that has a body which implements `hyper::body::Body`
> 
> ## Checklist
> * [x]  Tests are added
> * [x]  CHANGELOG entry is added
> * [x]  ~Documentation is updated~ (not required)
=> Add support for `Request<T>` where `T` is a type that implements `hyper::body::Body` trait

juniper_axum/CHANGELOG.md, juniper_axum/src/extract.rs
Check media type using `starts_with` instead of full string matching.
Fixes #1288
=> Fix content-header parsing in juniper_axum

juniper/CHANGELOG.md, juniper/src/ast.rs, juniper/src/executor/mod.rs, juniper/src/parser/document.rs, juniper/src/parser/tests/document.rs, juniper/src/validation/input_value.rs, juniper/src/validation/visitor.rs
Part of #1347
`VariableDefinitions` was renamed to `VariablesDefinition` in [GraphQL spec September 2025](https://spec.graphql.org/September2025):
- graphql/graphql-spec#916
Rename all the related items.
=> Rename `VariableDefinitions` to `VariablesDefinition` (#1347)
