- Cargo.toml
- src/integrations/serde.rs
serde 0.9.0 introduces breaking changes. See the release notes for more
details: <https://github.com/serde-rs/serde/releases/tag/v0.9.0>.
> Update to serde 0.9

- Cargo.toml
- src/integrations/serde.rs
serde 1.0.0 introduces breaking changes. See the release notes for more
details: <https://github.com/serde-rs/serde/releases/tag/v1.0.0>.
Fixes #50
> Upgrade to serde 1.0

- appveyor.yml
> Appveyor: Start using cargo-make.

- juniper/Cargo.toml
- juniper/src/integrations/mod.rs
- juniper/src/integrations/uuid.rs
- juniper/src/lib.rs
> uuid feature: Implement uuid::Uuid as a scalar type

- juniper/Cargo.toml
- juniper/src/integrations/mod.rs
- juniper/src/integrations/url.rs
- juniper/src/lib.rs
Essentially the same as https://github.com/graphql-rust/juniper/pull/89.
> url feature: Implement url::Url as a scalar type

- juniper/Cargo.toml
- juniper/src/ast.rs
- juniper/src/integrations/chrono.rs
- juniper/src/integrations/mod.rs
- juniper/src/lib.rs
- juniper/src/value.rs
Fixes https://github.com/graphql-rust/juniper/issues/87
> chrono feature: Implement GraphQLType for chrono::NaiveDate and chrono::DateTime

- juniper/src/http.rs
> Serialize on GraphQLRequest

- .travis.yml
- README.md
I think this would really help in both providing you and the community feedback of the code quality of juniper and help you see where the library is missing tests.
> Generate coverage report in travis build and upload to codecov

- juniper/src/executor_tests/executor.rs
> Add failing test for list of non-null items

- juniper/src/http.rs
- juniper_rocket/src/lib.rs
Also as part of this change I fixed and enabled
the http integration tests for Rocket.
Fixes https://github.com/graphql-rust/juniper/issues/116.
> url_decode parameters in Rocket integration

- juniper_iron/CHANGELOG.md
- juniper_iron/Cargo.toml
* Allow both iron 0.5 and 0.6
* Allow both urlencoded 0.5 and 0.6
> (iron) Update to iron 0.6

- Cargo.toml
- README.md
- juniper/src/http/mod.rs
- juniper_hyper/.gitignore
- juniper_hyper/Cargo.toml
- juniper_hyper/LICENSE
- juniper_hyper/Makefile.toml
- juniper_hyper/README.md
- juniper_hyper/examples/hyper_server.rs
- juniper_hyper/src/lib.rs
> WIP: Hyper integration

- juniper_hyper/Cargo.toml
- juniper_hyper/src/lib.rs
This allows us to publish `juniper_hyper`
> Use the crates.io version of reqwest

- README.md
- _build/azure-pipelines-template.yml
- azure-pipelines.yml
Note this doesn't remove the other CI providers yet.
> Set up CI with Azure Pipelines

- juniper/src/types/scalars.rs
As suggested in https://github.com/graphql-rust/juniper/issues/282#issuecomment-442854714
> Add new method to ID  scalar

- integration_tests/juniper_tests/src/custom_scalar.rs
- juniper/CHANGELOG.md
- juniper/src/value/scalar.rs
- juniper_codegen/src/derive_scalar_value.rs
- juniper_codegen/src/lib.rs
Fixes https://github.com/graphql-rust/juniper/issues/299.
> Rename ScalarValue derive

- juniper/src/tests/introspection_tests.rs
This was throwing a warning during compiling.
> Remove unused crate

- juniper/src/executor/look_ahead.rs
> Fix lookahead for optional variables

- juniper/src/tests/introspection_tests.rs
- juniper/src/tests/mod.rs
- juniper/src/tests/query_tests.rs
- juniper/src/tests/schema.rs
- juniper_hyper/examples/hyper_server.rs
- juniper_hyper/src/lib.rs
- juniper_iron/examples/iron_server.rs
- juniper_iron/src/lib.rs
- juniper_rocket/examples/rocket_server.rs
- juniper_rocket/src/lib.rs
- juniper_warp/examples/warp_server.rs
- juniper_warp/src/lib.rs
Closes https://github.com/graphql-rust/juniper/issues/308
> Split Query and Database types in example schema

- juniper_codegen/src/impl_object.rs
Just realized that I can pull the `path` variable up one level and deduplicate the `path.segments.iter().last().unwrap().ident.to_string()` part.
> Cleanup after #385

- juniper/src/macros/object.rs
> Fix broken doc link.

- juniper/src/types/scalars.rs
Fixes https://github.com/graphql-rust/juniper/issues/439.
> Make EmptyMutation `Send`

- juniper/Cargo.toml
- juniper/src/macros/scalar.rs
- juniper/src/schema/schema.rs
- juniper/src/types/async_await.rs
- juniper/src/types/containers.rs
- juniper/src/types/pointers.rs
- juniper/src/types/scalars.rs
- juniper_codegen/src/derive_enum.rs
- juniper_codegen/src/util.rs
Revert adding `async-trait` for `GraphQLType` (in #452)
> Remove async trait from `async-await`

- juniper/src/http/graphiql.rs
https://github.com/graphql/graphiql/releases
> Bump to latest graphiql

- integration_tests/async_await/src/main.rs
- juniper/src/lib.rs
This PR is intended to add the validation of the requested document in the async executor.
> Added usage of context validator in the async executor

- integration_tests/juniper_tests/src/codegen/derive_object_with_raw_idents.rs
- juniper/src/ast.rs
- juniper/src/executor_tests/executor.rs
- juniper/src/executor_tests/introspection/input_object.rs
- juniper/src/macros/tests/args.rs
- juniper/src/util.rs
- juniper_codegen/src/derive_input_object.rs
> More clippy and warnings.

- examples/warp_subscriptions/src/main.rs
Added `Sec-WebSocket-Protocol` header to avoid clients refusing connections.
> fix: websocket connection in subscriptions example

- juniper/CHANGELOG.md
- juniper/src/lib.rs
- juniper_hyper/src/lib.rs
- juniper_iron/src/lib.rs
- juniper_rocket/src/lib.rs
- juniper_rocket_async/src/lib.rs
- juniper_warp/src/lib.rs
> Move graphiql export location

- juniper/src/http/mod.rs
This is a minor improvement which eliminates unnecessary `Vec` collection of `GraphQLRequest`s before feeding them into `future::join_all()`, which is OK with accepting `Iterator`s anyway.
Additionally:
- Makes `GraphQLBatchRequest`/`GraphQLBatchResponse` code a bit more laconic.
> Avoid unnecessary Vec allocation when executing GraphQLBatchRequest

- juniper/src/value/scalar.rs
> Fix a minor typo in a comment

- docs/book/content/types/objects/error_handling.md
Documented the process in https://github.com/graphql-rust/juniper/issues/602.
Would be nice if someone could proof read the additions. Please mark sections which are not **immediately** clear or have weird grammar.
> Documented Alternative Error Handling

- juniper_warp/src/lib.rs
The `sink_rx` split from `websocket` will output endless Err(_) when error happened. Causing 100% cpu usage.
Use `try_fold` to return when the first error occurred.
> fix: endless poll on an errored ws stream

- juniper_actix/Cargo.toml
- juniper_warp/Cargo.toml
- juniper_warp/src/lib.rs
Failure package is no more maintained. So, I have removed that in favor of thiserror and anyhow. Both package is suggested by Failure maintainer for replacement. 
This is my first PR for this project. So, feedback is always welcome.
> failure removed in favour of thiserror and anyhow

- benches/bench.rs
- integration_tests/codegen_fail/fail/input-object/derive_incompatible_object.stderr
- integration_tests/codegen_fail/fail/interface/impl_argument_no_object.stderr
- integration_tests/codegen_fail/fail/object/impl_argument_no_object.stderr
- integration_tests/codegen_fail/fail/union/enum_non_object_variant.stderr
- integration_tests/codegen_fail/fail/union/enum_same_type_ugly.stderr
- integration_tests/codegen_fail/fail/union/struct_non_object_variant.stderr
- integration_tests/codegen_fail/fail/union/struct_same_type_ugly.stderr
- integration_tests/codegen_fail/fail/union/trait_fail_infer_context.stderr
- integration_tests/codegen_fail/fail/union/trait_non_object_variant.stderr
- integration_tests/codegen_fail/fail/union/trait_same_type_ugly.stderr
- juniper/src/tests/fixtures/mod.rs
- juniper/src/tests/fixtures/starwars/schema_language.rs
- juniper_rocket/src/lib.rs
- juniper_rocket_async/src/lib.rs
The messages appear to have changed on nightly
> Update compile fail tests for latest Rust

- juniper_iron/src/lib.rs
- juniper_rocket_async/src/lib.rs
https://github.com/SergioBenitez/Rocket/commit/549c9241c41320fc5af76b53c2ffc3bd8db88f8c
> Fix compilation of juniper_rocket_async: add limit to Data::open() call

- juniper_rocket_async/src/lib.rs
This should fix the current build failures.
https://github.com/SergioBenitez/Rocket/commit/52320020bc26387b96a0126a0d49821ad3125e7d
> juniper_rocket_async/ - Change Cookies to CookieJar

- docs/book/content/quickstart.md
I have found a number of issues with The Book.  I'm willing to make some pull requests to clean up said issues.  I am submitting this small and simple pull request as a hello-pull-request to get the ball rolling. If you all would rather I amend this to include more issues, then please let me know and I will.
> Fix version.

- juniper/src/types/scalars.rs
> impl Display for ID

- integration_tests/juniper_tests/src/codegen/union_derive.rs
- juniper/src/types/marker.rs
> Add missing marker trait impls for container types

- juniper_actix/examples/actix_server.rs
A smaller example is esier to understand.
Fixes #804
> Make the actix example self contained

- juniper_rocket_async/Cargo.toml
- juniper_rocket_async/src/lib.rs
Recent Rocket updates changed the way of handling Forms.
This PR updates the code to match with the current master.
> Update juniper_rocket_async for the latest Rocket master

- docs/book/content/servers/third-party.md
updates some recently broken links and clarifies content of section as examples
> update third-party examples in book

- integration_tests/juniper_tests/src/issue_922.rs
- integration_tests/juniper_tests/src/lib.rs
- juniper/CHANGELOG.md
- juniper/src/types/async_await.rs
- juniper/src/types/base.rs
> Fix fields on interface not being resolved when used with fragments

- integration_tests/juniper_tests/src/codegen/impl_scalar.rs
- juniper_codegen/src/impl_scalar.rs
Fix https://github.com/graphql-rust/juniper/issues/877
> Fix using graphql_scalar proc macro inside a macro

- juniper_rocket/CHANGELOG.md
- juniper_rocket/Cargo.toml
- juniper_rocket/src/lib.rs
There was a regression:
https://github.com/SergioBenitez/Rocket/issues/1647
Fixes https://github.com/graphql-rust/juniper/issues/939.
> Support latest rocket 0.4

- docs/book/content/advanced/subscriptions.md
- docs/book/tests/Cargo.toml
- examples/actix_subscriptions/Cargo.toml
- examples/actix_subscriptions/src/main.rs
- examples/basic_subscriptions/Cargo.toml
- examples/basic_subscriptions/src/main.rs
- examples/warp_async/Cargo.toml
- examples/warp_subscriptions/Cargo.toml
- examples/warp_subscriptions/src/main.rs
- integration_tests/async_await/Cargo.toml
- integration_tests/async_await/src/main.rs
- integration_tests/codegen_fail/Cargo.toml
- integration_tests/juniper_tests/Cargo.toml
- juniper/Cargo.toml
- juniper/src/executor_tests/async_await/mod.rs
- juniper_actix/Cargo.toml
- juniper_actix/examples/actix_server.rs
- juniper_actix/src/lib.rs
- juniper_benchmarks/Cargo.toml
- juniper_graphql_ws/Cargo.toml
- juniper_graphql_ws/src/lib.rs
- juniper_hyper/Cargo.toml
- juniper_hyper/examples/hyper_server.rs
- juniper_hyper/src/lib.rs
- juniper_rocket/Cargo.toml
- juniper_rocket/src/lib.rs
- juniper_subscriptions/Cargo.toml
- juniper_warp/Cargo.toml
- juniper_warp/src/lib.rs
- `tokio = 1`
- `warp = 0.3`
- `hyper = 0.14`
- `actix = 4.0.0-beta.5`
> Upgraded tokio, warp, hyper and actix

- examples/actix_subscriptions/Cargo.toml
- examples/actix_subscriptions/src/main.rs
- juniper_actix/Cargo.toml
- juniper_actix/examples/actix_server.rs
- juniper_actix/src/lib.rs
At the moment it's a work in progress since version 4 is still in development at the beta stage.
> Actix 4 support

- integration_tests/async_await/src/main.rs
- juniper/src/executor/look_ahead.rs
- juniper/src/executor/mod.rs
- juniper/src/http/mod.rs
- juniper/src/lib.rs
- juniper/src/parser/utils.rs
- juniper/src/schema/meta.rs
- juniper/src/schema/translate/graphql_parser.rs
- juniper/src/tests/fixtures/starwars/schema.rs
- juniper/src/types/async_await.rs
- juniper/src/types/base.rs
- juniper/src/types/subscriptions.rs
- juniper/src/validation/input_value.rs
- juniper/src/validation/rules/known_argument_names.rs
- juniper/src/validation/rules/known_directives.rs
- juniper/src/validation/rules/overlapping_fields_can_be_merged.rs
- juniper/src/validation/rules/variables_in_allowed_position.rs
- juniper_actix/src/lib.rs
- juniper_codegen/src/common/field/arg.rs
- juniper_codegen/src/util/mod.rs
- juniper_warp/src/lib.rs
This PR fixes all current clippy warnings
> Fix clippy warnings

- examples/README.md
I placed this directly into the examples folder, so in the location must folks will run the code from.
Resolves: #1122
> Add documentation on how to run examples

- .github/workflows/ci.yml
See https://doc.rust-lang.org/nightly/rustc/platform-support/wasm32-wasip1.html
> Switch from `wasi` to `wasip1` in ci.yml

- juniper/Cargo.toml
- juniper_axum/CHANGELOG.md
- juniper_axum/Cargo.toml
- juniper_axum/src/extract.rs
- juniper_axum/src/subscriptions.rs
- juniper_axum/tests/ws_test_suite.rs
Mirror of #1303  
Also resolves #1305
Since the original author (@jgrund) became unresponsive.
>  Upgrade `axum` to 0.8 (#1303)
